### ISSUE TITLE
Resource leak: Too many open files error

### ISSUE THREAD

**Issue by winterstein** [searchbox-io/Jest#136]
I tried making fresh JestClients for requests. This led to a "too many files open" IOException. Adding in calls to JestClient.shutdownClient does not fix this.

This was originally posted as #135, where a workaround is discussed -- using a singleton JestClient. That works as a workaround, but the underlying resource leak is still a bug.

**Comment by oxymor0n** [comment]
Checking in to report that the resource leak is still there as of version 2.0.2 if one doesn't follow the singleton pattern. I guess it is the maintainer's prerogative to recommend this particular usage pattern, but the resource leak is still a bug that should be addressed. At the very least, it should be highlighted in the README to explain the necessity of using the singleton pattern.
