### ISSUE TITLE
Support for aggregation framework

### ISSUE THREAD

**Issue by hlassiege** [searchbox-io/Jest#146]
Hi,

I'm wondering if the support of the aggregation framework is under work ? 

Thanks

**Comment by cfstout** [comment]
Is this still an open issue? Looks like there was some work done previously, but I don't see aggregation support anywhere in the code or in open PRs. I'd be happy to take a crack at it if it's still an open issue.

**Comment by kramer** [comment]
Hi @cfstout,

Yes this is still an open issue, feel free to give it a go and we'll be more than happy to accept it.

Pinging @ferhatsb who mentioned he might have an idea on the matter some time ago :smile: !

**Comment by cfstout** [comment]
Aggregations introduce the notion of nesting. As this is difficult to handle from the Jest side, I'm going to add documentation to the aggregation class saying that parsing for nested aggregations must happen on the user's side. If not we would have to know the specific name of each aggregation while parsing out into the various Aggregation models used greatly complicating the code. Let me know if that sounds ok.

That being said I've gone ahead and created aggregation models for all the other aggregations except the ones elasticsearch lists as "experimental", but that is my next step. Progress is in my fork: https://github.com/cfstout/Jest/tree/Aggregation_support

**Comment by cfstout** [comment]
Seems elasticsearch also removed the _type field in aggregations, so we can't follow the same pattern used by facets. I am going to try a different approach by having a single aggregation model, with all of the possible aggregation fields, and a list of sub aggregations. Basically, my plan is to create a java pojo representation of the json object adding some back-end logic to make the aggregations easy to deal with.

**Comment by cfstout** [comment]
Just pushed a 'hacky' version to my branch that returns aggregations with fields without knowing about type. My plan is to now override the getAggregations method in the SearchResult class to also take a name to type map, which would allow the user to provide the specific type of aggregation requested and the associated name. That way when we encounter the name in the json document, we simply perform a lookup in the table as opposed to looking at the _type metadata field present before. Then we can recursively pass down this map to the aggregations themselves to handle the nested use case also.

**Comment by cfstout** [comment]
I just pushed a draft of this aggregation module. See commit ^. @kramer I'd love some feedback just whenever you have some free time before I continue with polishing and writing tests for this code.
