### ISSUE TITLE
GSON Date format does not match default Elasticsearch date format

### ISSUE THREAD

**Issue by MinCha** [searchbox-io/Jest#165]
Hello.

I have a question about date format.

In `AbstractJestClient`:
`public static final String ELASTIC_SEARCH_DATE_FORMAT = "yyyy-MM-dd'T'hh:mm:ssZ";`

Is this intended? I wonder if you meant `yyyy-MM-dd'T'HH:mm:ssZ`. Because it looks like it is losing hour information at PM.

Thanks for reading.

**Comment by micw** [comment]
@kramer Thank you for fixing this issue. Could you please schedule a relase for this fix? IMO it's a serious issue because it corrupts data stored to ES.
Kind regards,
Michael.

**Comment by kramer** [comment]
Hey @micw , v0.1.5 is now scheduled for 8th of February.
