### ISSUE TITLE
How to query matadata using jest

### ISSUE THREAD

**Issue by mygitrepo** [searchbox-io/Jest#168]
Hello,

My query result (match all) using head plugin search: `locahost:9200/mydb/mycollect/_search`

```
{

    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
            {
                "_index": "mydb",
                "_type": "mycollect",
                "_id": "54ac6333b760d23c7635ce0b",
                "_score": 1,
                "_source": {
                    "content": {
                        "_content_type": "String",
                        "_title": "def.xml",
                        "_content": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI"
                    },
                    "filename": "def.xml",
                    "contentType": "String",
                    "md5": "4f5cfde85d1b6f48658b82af980714c7",
                    "length": 2438,
                    "chunkSize": 261120,
                    "uploadDate": "2015-01-06T22:35:31.289Z",
                    "metadata": {
                        "Description": "def XML File",
                        "tags": [
                            "def"
                            ,
                            "XML"
                        ]
                    }
                }
            }
        ]
    }

}
```

I'm able to find "filename". But wondering how do I fetch "Description" & "tags" fields from "metadata".

I'm using Jest client to execute search which is not returning "Description" field contents:

```
SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
searchSourceBuilder.query(QueryBuilders.wildcardQuery("Description", "*"));

Search search = new Search.Builder(searchSourceBuilder.toString())
                                         // multiple index or types can be added.
                                         .addIndex("mydb")          
                                         .addType("mycollect")
                                         .build();
```

Appreciate your help.

**Comment by kramer** [comment]
In its most raw form you can do `result.getJsonObject()` and navigate the Json from there; what exactly are you asking?

**Comment by mygitrepo** [comment]
I can get root pojo object field (For ex filename) using:

@jestid
private String filename;

public String getfilename() {
    	return filename;

But "metadata" is nested pojo object and I want to fetch fields "Description" and "tags" under it.

With following code I can access complete object:

private Object metada;

public Object getMetadata() {
        return metadata;
}

It is displayed as: {tags=[def, XML]}

How can I access individual elements of "tags" array ? So that it will be displayed as:

[def, XML]

Thanks !

**Comment by tomsen-san** [comment]
I suppose you would have to model the complete structure under _source and have POJOs for the nested objects. gson does the rest if member names match. Have you tried that? From your code it does not seem to be the case. 
Not sure about the 'Description'-field though. Since it starts upper-case this might be a problem matching the setter in a POJO.

**Comment by kramer** [comment]
Closing this issue as no update was made in a long time. Please feel free to reopen if you come up with any new information.
