### ISSUE TITLE
Does jest support suggester? Can you give me an example?

### ISSUE THREAD

**Issue by stonetao** [searchbox-io/Jest#170]
Does jest support suggester, if it supports, can someone give me am example. I went though the document, but didn't find. Thank you. 
I want to use something like something like localhost:9200/index/_suggest

**Comment by kramer** [comment]
No, not yet at least, see #30.

**Comment by ferhatsb** [comment]
You can use "_search" endpoint to get suggestions. Adding _suggest endpoint is not a big deal though.

**Comment by stonetao** [comment]
I am new to elasticsearch, after reading the document I have found the way to get suggestion from "_search" endpoint. Thank you.
