### ISSUE TITLE
Support annotation to specify source fields of POJO

### ISSUE THREAD

**Issue by lenyt** [searchbox-io/Jest#172]
Hi,

It would be useful to have a @Source or @JestSource annotation which allows for specifying which fields in a POJO should be included as part of source when indexing. In many cases a POJO is not specifically for indexing only so contains many fields that don't need to be sent as part of source to ElasticSearch when indexing.

Regards,
Len

**Comment by kramer** [comment]
Since Gson is used for serialization you can customize this process with any of the Gson supported modifiers/annotations including [Field Exclusion](https://sites.google.com/site/gson/gson-user-guide#TOC-Excluding-Fields-From-Serialization-and-Deserialization).
