### ISSUE TITLE
Simple cluster info query

### ISSUE THREAD

**Issue by n0k** [searchbox-io/Jest#177]
Hi,

I'm new to using Jest and was wondering how to construct a query like 

curl 'http://localhost:9200/?pretty'

using the Jest HTTP client.

Thanks.

**Comment by kramer** [comment]
Please read the [docs](https://github.com/searchbox-io/Jest/tree/master/jest) and [integration tests](https://github.com/searchbox-io/Jest/tree/master/jest/src/test/java/io/searchbox/core) for usage examples. Most of the time you need to find the `Action` implementing class that is corresponding to the API you want to use and then pass an instance of it to client...
