### ISSUE TITLE
Is there a plan to add authentication support?

### ISSUE THREAD

**Issue by maphysics** [searchbox-io/Jest#178]
Hi 

Is there a plan to add support for basic authentication?  For both those of us on hosted clusters and now that shield is here?

**Comment by kramer** [comment]
Hi,

No plans so far. You can modify the internal http client to use authentication of your choice (as mentioned in #34) but yes obviously a more straightforward way of doing it would be nicer.

**Comment by maphysics** [comment]
Thanks I found what I needed on that thread!
