### ISSUE TITLE
@JestId annotation not found in super class

### ISSUE THREAD

**Issue by tomsen-san** [searchbox-io/Jest#181]
I would like to suggest an enhancement.
We have a family of documents which share a number of fields and we wanted to separate out the common fields into a super class from which all document types inherit. Particularly the id-field is common to all document types.
The code which looks for the @JestId annotation does not seem to traverse the class hierarchy up in an attempt to find the annotation? 
Btw, spring does it so why don't we?

**Comment by dmarko484** [comment]
The same here. Is there any workaround on this?

**Comment by tomsen-san** [comment]
Well, one can still use super classes, it's just the id-field which has to
be annotated in every leaf class. A fix for this is not hard, a traversal
up the class hierarchy to to look for the id-annotation is all it takes. I
see if I can propose something over Chrismas :-)

-Thomas

David Marko <notifications@github.com> schrieb am Di., 10. Nov. 2015 um
16:26 Uhr:
