### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by ravinaik1312** [searchbox-io/Jest#184]
Does Jest support pagination?
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/pagination.html

I am getting a SearchResult from elastic search and I want it to return 'n' (size) results from it and in the continuing call return the next 'n' results. 

Something like this from the Elastic Search Java api,

SearchResponse response = client.prepareSearch("index1", "index2")
        .setTypes("type1", "type2")
        .setSearchType(SearchType.DFS_QUERY_THEN_FETCH)
        .setQuery(QueryBuilders.termQuery("multi", "test"))             // Query
        .setPostFilter(FilterBuilders.rangeFilter("age").from(12).to(18))   // Filter
        .setFrom(0).setSize(60).setExplain(true) // Like this
        .execute()
        .actionGet(); 

Thanks!

**Comment by kramer** [comment]
Yes. Since it's just generic HTTP parameter use the `setParameter` method on builder:

`JestResult result = client.execute(new Search.Builder(query).setParameter("size", 5).setParameter("from", 10).build());`

**Comment by ravinaik1312** [comment]
Thanks!

**Comment by maksimu** [comment]
@ravinaik1312 I know it might be too late, but just in case if you or somebody else will find this useful, I wrote a helper method for myself to convert List to Spring's Pagination:

```
public class ElasticSearchHelpers<T> {

    public Page<T> toPage(int currentPageNumber, int pageSize, String sortOrder, String fieldToSortBy, List<T> data, int totalCount){
        Pageable pageable = new PageRequest(currentPageNumber, pageSize, new Sort(Sort.Direction.fromString(sortOrder), fieldToSortBy));
        Page<T> p = new PageImpl<>(data, pageable , totalCount);
        return p;
    }
}
```

and then use it like this:

```
ElasticSearchHelpers<ContactsIndex> elasticSearchHelpers = new ElasticSearchHelpers<>();

Search search = new Search.Builder(searchSourceBuilder.toString())
                .addIndex(PROVIDER_INDEX_NAME).addType(PROVIDER_INDEX_TYPE)
                        // start adding pagination
                .setParameter("size", pageSize)
                .setParameter("from", pageNumber)
                        // stop adding pagination
                .build();

JestResult result = jestClient.execute(search);

List<ContactsIndex> contactsFoundList = result.getSourceAsObjectList(ContactsIndex.class);

JsonObject jsonObject = result.getJsonObject();
int totalCount = jsonObject.getAsJsonObject("hits").getAsJsonPrimitive("total").getAsInt();

Page<ContactsIndex> providerIndexePage = elasticSearchHelpers.toPage(pageNumber, pageSize, sortOrder, fieldToOrder, contactsFoundList, totalCount);

```
