### ISSUE TITLE
Sub-aggregations available at the wrong level for bucketing aggregations

### ISSUE THREAD

**Issue by cfstout** [searchbox-io/Jest#187]
I just realized that the implementation of Aggregations is not entirely correct. All bucketing aggregations:
```
FilterAggregation
GeohashGridAggregation
HistogramAggregation
DateHistogramAggregation
RangeAggregation
Ipv4RangeAggregation
DateRangeAggregation
GeoDistanceAggregation
SignificantTermsAggregation
TermsAggregation
```
Should have sub aggregations available from the buckets they return as opposed to their specific aggregation root. I think we can fix by having each of these aggregations have a shared abstract Bucket object that each of their internal structures extends. Then bucket could be an extension of Aggregation, storing the json root of the bucket which would give access to sub-aggregations.

**Comment by kramer** [comment]
Hmm good point. Maybe we also should *not* expose `getAggregation` methods on a bucketing aggregation because it does not make sense (and I doubt it's valid on ES side)? Then there would also be no point for a bucketing aggr to extend the `Aggregation` class... am I missing something?

**Comment by cfstout** [comment]
Yes I think that that is correct. If we don't have them extend Aggregation I think we would have to move the name and jsonRoot variables into the class themselves as well as the getter methods, but that seems to make sense.

**Comment by cfstout** [comment]
I just took a stab at this, and if we remove the extension of the `Aggregation` class for the bucketing aggregations then calling `getAggregation("range", RangeAggregation.class)` for instance will no longer work which is unfortunate..

**Comment by cfstout** [comment]
I submitted a PR for this fix a little over a week ago. Any ETA on when I can get some feedback?

**Comment by kramer** [comment]
PR is now merged.
