### ISSUE TITLE
Putting settings without ImmutableSettings class

### ISSUE THREAD

**Issue by rutgervanwilligen** [searchbox-io/Jest#192]
Hi!

In my project, I'm using Jest to be able to communicate to Elasticsearch without the need of including Elasticsearch dependencies in my pom. For putting a mapping, creating an index and querying this is working excellent. However, it seems that for putting settings through Jest, using the `ImmutableSettings` class from the ES libraries is necessary. Is there a way of putting settings without using this class?

**Comment by kramer** [comment]
Hi @rutgervanwilligen 

Sorry for the late reply. I'm not sure what type of settings you want to put, if it is cluster settings then we have `io.searchbox.cluster.UpdateSettings` and if it is index settings then we have `io.searchbox.indices.settingsUpdateSettings` both of which takes any object as the payload, so you can just supply the appropriate JSON string (or a map) if you'd like.

Please feel free to re-open this issue if it was not resolved.
