### ISSUE TITLE
Handling couchbase-elasticsearch documents

### ISSUE THREAD

**Issue by rjshah** [searchbox-io/Jest#194]
Hi,

I am using the elasticsearch-transport-couchbase-2.0.0 plugin to automatically create document metadata into elasticsearch (As documented on couchbase site). As per this, metadata of relevant documents will be XDCR'ed into the ElasticSearch cluster. The actual documents will be persisted in Couchbase cluster. 
On running the following on elasticsearch -> `get test-rest-jest/_search?q="Mumbai"`
result I get is :
```
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 2,
      "max_score": 1.0565116,
      "hits": [
         {
            "_index": "test-rest-jest",
            "_type": "couchbaseDocument",
            "_id": "1001",
            "_score": 1.0565116,
            "_source": {
               "doc": {
                  "propertyId": "1001",
                  "numberOfSingleBedRoomsReserved": 1,
                  "numberOfDoubleBedRooms": 10,
                  "name": "Hotel Mumbai Nariman Point",
                  "numberOfDoubleBedRoomsReserved": 1,
                  "numberOfSingleBedRooms": 10,
                  "rooms": [
                     {
                        "roomType": "DoubleBedRoom",
                        "roomReserved": true,
                        "roomId": "1001_01"
                     }, ........
```

As shown in the above response sample, the actual output I am interested is inside the hits->hits->_source->doc of the elasticsearch response. 

I tried using various options on the SearchResult, to get the response inside the `hits->hits->_source->doc` converted to my 'Property' POJO. But no success. 

The code to search for documents using Jest:

		SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
		searchSourceBuilder.query(QueryBuilders.matchQuery("name", "Mumbai"));
		Search search = new Search.Builder(searchSourceBuilder.toString())
		                                .addIndex("test-rest-jest")
		                                .addType("couchbaseDocument")
		                                .build();
                SearchResult result = client.execute(search);

I have a POJO created for the expected response:

```
public class Property {
	private String name;
	private int numberOfSingleBedRooms;
	private int numberOfDoubleBedRooms;
	private String propertyId;
	private int numberOfSingleBedRoomsReserved;
	private int numberOfDoubleBedRoomsReserved;
	ArrayList<Rooms> rooms;
        .........
        .........
```

Finally I had to use the following code to get hold of 'Property' POJO

```
		JsonObject jObj = result.getJsonObject();		
		JsonObject jObj1 = jObj.getAsJsonObject("hits");
		JsonArray jObj2 = jObj1.getAsJsonArray("hits");
		if(jObj2.size()==0) {
			System.out.println("Try some other search");
		}
		Iterator<JsonElement> it = jObj2.iterator();		
		JsonElement jsonEl = null;
		Gson gson = new Gson();
		Property property = null;
		while(it.hasNext()) {
			jsonEl = it.next();
			if(jsonEl.isJsonObject()) {
				JsonObject jObj3 = jsonEl.getAsJsonObject();
				JsonObject jObj4 = jObj3.getAsJsonObject("_source");
				JsonObject jObj5 = jObj4.getAsJsonObject("doc");
				property = gson.fromJson(jObj5, Property.class);
				System.out.println("property = "+property);
			}
		}
```

Is there any way of getting the relevant POJO under hits->hits->_source->doc of the ElasticSearch response??

**Comment by kramer** [comment]
Hi @rjshah 

Sorry for the late reply. `SearchResult` has a `getHits` method which will convert the JSON source in the default path `hits->hits->_source` to the type you provide. Since you are not interested in the default path there are 2 things you can do:

* Make a wrapper class for your POJO so Gson can convert using default structure.
```
public class PropertyWrapper {
   public Property doc;
}
```

* Extend `SearchResult` to suit your custom doc path (you can't call the constructor as in this example yet, but you'll be able to with v0.1.6):
```
public class CustomSearchResult extends SearchResult {

    public CustomSearchResult(SearchResult searchResult) {
        super(searchResult);
    }

    @Override
    protected <T, K> Hit<T, K> extractHit(Class<T> sourceType, Class<K> explanationType, JsonElement hitElement, String sourceKey) {
        return super.extractHit(sourceType, explanationType, hitElement.getAsJsonObject().get("doc"), sourceKey);
    }
}

...

CustomSearchResult result = new CustomSearchResult(client.execute(search));
```


Please feel free to reopen the issue if you are still having trouble.
