### ISSUE TITLE
Sorting on string field

### ISSUE THREAD

**Issue by jtruty** [searchbox-io/Jest#197]
Is this supported? I get this error when trying to extract Hits from the searchResult:
    Line | Method
->>  540 | parseDouble             in java.lang.Double
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    193 | getAsDouble             in com.google.gson.JsonPrimitive
|    120 | extractSort . . . . . . in io.searchbox.core.SearchResult

It seems the sorts are hardcoded to doubles in this class. Is there another way to get the hits out of a search result when sorting on string fields?

**Comment by kramer** [comment]
You're right, we missed that when merging #188.
