### ISSUE TITLE
Difficulty marshalling bulk response

### ISSUE THREAD

**Issue by jtruty** [searchbox-io/Jest#201]
I am having difficultly marshalling the Bulk Response into an Elasticsearch BulkResponse. I try to do this:
```java
JsonElement response = jestResult.getJsonObject();
BulkResponse bulkResponse = gson.fromJson(response, BulkResponse.class);
```
However, this is not successful. The integration tests aren't very helpful here. Do I need to use the readFrom method in the BulkResponse class?

**Comment by kramer** [comment]
There is no support for marshalling any of the rest/json responses to Elasticsearch's (transport channel intended) classes.

**Comment by jtruty** [comment]
What is the recommended method for handling the index response? Just get at the individual fields?

**Comment by kramer** [comment]
> Just get at the individual fields?

Pretty much, yeah.

**Comment by jtruty** [comment]
That works, just wanted to know if I was missing something. Thanks!
