### ISSUE TITLE
Updating a whole document example

### ISSUE THREAD

**Issue by mastermind1981** [searchbox-io/Jest#202]
Hi,

First of all, i thank you for your great effort to provide this client.

I have a case where should i update a document and i haven't seen an example of updating a whole one?

Is this possible via Jest?

Thanks in advance,

**Comment by kramer** [comment]
Nothing that is Jest specific here; if you want to do a "whole document" update then just follow the [related section in Elasticsearch guide](http://www.elastic.co/guide/en/elasticsearch/guide/master/update-doc.html) (which is basically sending an index request -`Index` action in Jest- against the `id` of the document you want to replace/full-update).

**Comment by kramer** [comment]
Closing as answered (also in [Stackoverflow](http://stackoverflow.com/questions/30222880/elasticsearch-jest-update-a-whole-document/30233561#30233561)).
