### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils

### ISSUE THREAD

**Issue by SuperveS** [searchbox-io/Jest#203]
Hi,

I just added Jest maven repo and every time i try to run it fails due to missing class exception.
java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils

i can clearly see (seen in attached pic) that i have that class under Maven dependencies so i cannot understand where the problem comes from.

any help appreciated. thanks

![missingclassexc](https://cloud.githubusercontent.com/assets/8070047/7666708/5e16ca28-fbf7-11e4-9261-5eeff7251bda.JPG)

**Comment by kramer** [comment]
Most probably your runtime classpath configuration is wrong; are you using maven for your project?

**Comment by SuperveS** [comment]
Thanks for the prompt response,
Yes, and i can see the maven in my classpass:
![image](https://cloud.githubusercontent.com/assets/8070047/7666727/703286a6-fbf8-11e4-9ee4-1cec3aeca67b.png)

**Comment by kramer** [comment]
Well then it looks like some sort of maven-eclipse integration problem (or misuse) of which I've no idea about. I'd suggest asking or searching in [stackoverflow](http://stackoverflow.com/search?q=eclipse+maven+noclassdeffounderror).

**Comment by SuperveS** [comment]
THanks,
I went through those guides with no luck.
problem remains.
I detached Maven and manually placed all JARs in the build path - problem remains...
added  appace-commons-lang-2.6  (together with 3.3.2) - problem remains...
any other ideas?

**Comment by kramer** [comment]
[Build path and classpath are two different things](http://stackoverflow.com/a/3529514/135503) and if you are getting this error during running the program and not when compiling it then you need to properly set up your classpath.

I'll be closing this as it is not a Jest specific/related issue, if you have reasonable doubt to suggest otherwise please reopen it.
