### ISSUE TITLE
MalformedJsonException

### ISSUE THREAD

**Issue by bitsofinfo** [searchbox-io/Jest#204]
Using the latest version of Jest. Created a Bulk request with a document with one field, the fields value has a double quote in it. I get this error:

```
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8
```

**Comment by kramer** [comment]
This test case indexes a document with one field whose value has a double quote in it and works without any errors:
```
@Test
public void bulkOperationWithIndex() throws IOException {
    Map<String, String> source = new HashMap<String, String>();
    source.put("user", "kimchy\"");
    Bulk bulk = new Bulk.Builder()
            .addAction(new Index.Builder(source).index("twitter").type("tweet").id("1").build())
            .build();
    JestResult result = client.execute(bulk);
    assertTrue(result.getErrorMessage(), result.isSucceeded());
}
```

Care to elaborate?

**Comment by bitsofinfo** [comment]
Nada, just a mis-diagnosis, I think this is fine.

**Comment by wasifaleem** [comment]
I just faced this issue.
This happened to me because ES is running behind a proxy(this is pretty common).
When request times out or ES goes down or proxy closes the connection, the response returned might not be JSON (In my case it was HTML from apache).

I think we can handle this more gracefully in `AbstractAction`'s ` parseResponseBody`
```java
    protected JsonObject parseResponseBody(String responseBody) {
        if (responseBody != null && !responseBody.trim().isEmpty()) {
            try {
                return new JsonParser().parse(responseBody).getAsJsonObject();
            } catch (JsonParseException e) {
                logger.warn("Error in parsing responseBody as JSON: {}", responseBody, e);
            }
        }
        return new JsonObject();
    }
```
