### ISSUE TITLE
Question: Is bulk update supported?

### ISSUE THREAD

**Issue by mastermind1981** [searchbox-io/Jest#205]
Hi,

I want to make a bulk update query but i don't know if it is supported or not by Jest.

I have tested it with the code below but it seems that is not working:

```
            Bulk.Builder bulkBuilder = new Bulk.Builder() ;
            bulkBuilder.defaultIndex(indexName);
            bulkBuilder.defaultType(mappingName);
            for (AdElasticDTO dto: dtos) {
                bulkBuilder.addAction(new Update.Builder(dto).id(dto.getId().toString())
                        .index(indexName).type(mappingName).build());
            }
            jestClient.execute(bulkBuilder.build());
```
Is it supported or am i missing something?

Thanks in advance,

**Comment by kramer** [comment]
Yes it is supported and it works, see [BulkIntegrationTest](https://github.com/searchbox-io/Jest/blob/4cf33edbf6eee6fd9e6ed710439337a0a944fe8d/jest/src/test/java/io/searchbox/core/BulkIntegrationTest.java#L147) for example.  

> "it seems that is not working".

Means what exactly?

**Comment by mastermind1981** [comment]
"it seems that is not working". it's about my code.

In the test case you are using a script, is POJO supported also like indexing or deleting, such as i wrote in my code?

Thanks

**Comment by kramer** [comment]
[Elasticsearch updates work with either partial docs or updates scripts](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html) and that is exactly what jest supports. To update a "full doc" you just send index request to the existing doc's id.

**Comment by mastermind1981** [comment]
@kramer Thank you very much.
