### ISSUE TITLE
bulk operation with upsert fails with DocumentMissingException

### ISSUE THREAD

**Issue by bitsofinfo** [searchbox-io/Jest#209]
We are building an Update request like this:

```
io.searchbox.core.Update.Builder requestBuilder = new Update
				.Builder(docJson)
				.index(myIndex)
				.type(indexType)
				.id(myDocId)
				.setParameter(ElasticSearchReservedWords.DOC_AS_UPSERT.getText(), true);
		
Update update = requestBuilder.build();

io.searchbox.core.Bulk.Builder bulkBuilder = new Bulk.Builder();
bulkBuilder.addAction(update);
```

We execute this bulk request and get an error like this back, not sure if we are building the Update request incorrectly for an upsert within a bulk or what. But given we want an upsert theoretically we should not get this kind of error back.

```
{"update":{"_index":"myIndex","_type":"user","_id":"921793a5-c982-48fa-b3b2-d6b530f8d882","status":404,"error":"DocumentMissingException[[myIndex][-1] [user][921793a5-c982-48fa-b3b2-d6b530f8d882]: document missing]"}}]
```

**Comment by kramer** [comment]
Not sure if related to the error you are getting but this `.setParameter(ElasticSearchReservedWords.DOC_AS_UPSERT.getText(), true);` makes no sense; `setParameter` method is for HTTP parameters (i.e.: `http://.../index/type/id?refresh=true`) but `doc_as_upsert` is a payload parameter (i.e.: `'{ "doc" : {"field" : "value"}, "doc_as_upsert" : true }'`).

**Comment by bitsofinfo** [comment]
k, so I will try this instead (is this what you are suggesting?)

```
io.searchbox.core.Update.Builder requestBuilder = new Update
                .Builder(docJson)
                .index(myIndex)
                .type(indexType)
                .id(myDocId)
                .setParameter("doc_as_upsert", true);
```

**Comment by kramer** [comment]
No. It needs be in your payload (`docJson`).

**Comment by bitsofinfo** [comment]
ahh, got it
