### ISSUE TITLE
Search.getRestMethodName should return "GET"

### ISSUE THREAD

**Issue by Lucas-C** [searchbox-io/Jest#214]
Everything is in the title :)
https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/core/Search.java#L58

**Comment by kramer** [comment]
Not really, `Search` action is built around [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html) which works with both GET and POST (and for compatibility sake we used the latter).

**Comment by Lucas-C** [comment]
My bad, I was really too quick to report an issue on this one.
For the record, I had a "Request method 'POST' not supported" error message because I was hitting the wrong api endpoint, and this other service did not support POST requests.
Silly mr

**Comment by kramer** [comment]
No probs, I wonder with which service you got that error though. :)

**Comment by Lucas-C** [comment]
As a side note, wiht the builder pattern, it is best to set the enclosing class constructor visibility to protected instead of private, so that the class can be subclassed:
- https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/core/Search.java#L23
- http://stackoverflow.com/a/17165079/636849

**Comment by Lucas-C** [comment]
The java REST web service I am building :P

**Comment by kramer** [comment]
> As a side note, wiht the builder pattern, it is best to set the enclosing class constructor visibility to protected instead of private, so that the class can be subclassed

Good point, we have it `public` in some classes and `private` in other as they carried it from past. A through unification and cleaning is due on those; thanks!

**Comment by Lucas-C** [comment]
No problem, thank you for the quick answer !
