### ISSUE TITLE
Client configuration setting are not applied to Async calls

### ISSUE THREAD

**Issue by iliasbartolini** [searchbox-io/Jest#219]
In the sample below when the query is executed the client connection settings (eg. maxTotalConnetion, defaultMaxTotalConnectionPerRoute, ...etc.) are not applied to a Async calls.

    val factory: JestClientFactory = new JestClientFactory()
    factory.setHttpClientConfig(new Builder(uri)
      .maxConnectionIdleTime(10, TimeUnit.SECONDS)
      .maxTotalConnection(50)
      .defaultMaxTotalConnectionPerRoute(30)
      .connTimeout(3000)
      .readTimeout(2000)
      .multiThreaded(true)
      .build())
    val jectClient = factory.getObject

    jestClient.executeAsync(search, handler)

**Comment by kramer** [comment]
Well this is embarrassing, looks like I forgot to set all those config objects (and more!) on the async client... will fix it asap.

In the meantime I'm open for ideas on how to test this as it seems hard to get the config values from the final client object.

**Comment by iliasbartolini** [comment]
Not sure how to help on the testing question but meanwhile I'm leaving here a note for a temporary workaround we adopted. Might be useful in case other people are reading this because stumbled on the same problem while it gets a proper fix.
We are just re-setting the HttpAsyncClient downcasting JestClient to JestHttpClient and using JestHttpClient.setAsyncClient(...)

    val client = factory.getObject
    client match {
      case jestHttpClient: JestHttpClient => {
        jestHttpClient.setAsyncClient(HttpAsyncClients.custom().setMaxConnPerRoute(...).setMaxConnTotal(...).build())
        jestHttpClient
      }

**Comment by cricanr** [comment]
Hi,

Do you have any information when this fix will be released? 

Thanks,
Radu

**Comment by kramer** [comment]
@cricanr next stable version release is planned for [16.08.2015](https://github.com/searchbox-io/Jest/wiki/Changelog#v017-16082015), in the meantime you can use the [snapshot](https://github.com/searchbox-io/Jest/tree/master/jest#snapshot).

**Comment by cricanr** [comment]
@kramer , ok, thanks for the info. We'll try then the snapshot :)
