### ISSUE TITLE
Missing? http status in JestResult

### ISSUE THREAD

**Issue by bartekbp** [searchbox-io/Jest#220]
Hi,

after using Jest for some time I've come across use cases where http status would be helpful e.g. We would like to ensure that index doesn't exist. 
One way to do this it is to always perform DeleteIndex action and check whether status is equal to 2XX or 404. Without http status in JestResult it's difficult. 
Is there any reason for not having this?

**Comment by kramer** [comment]
Status code is already used by the client to set the `isSucceeded` flag on result (true if 2XX, false otherwise).

**Comment by bartekbp** [comment]
Yes, but there are statuses for which there is no error message and 404 is one of them. So we would only get ```isSucceeded => false``` and nothing more.

**Comment by kramer** [comment]
And if we had the code in its own field then we would get `404` and nothing more, what difference does it make (considering all response codes from ES have binary meaning) ? :)

Regardless of that, if server returns non-2XX code and the response body is empty then [you still get the response code](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/action/AbstractAction.java#L77) in `getErrorMessage`.

**Comment by bartekbp** [comment]
I've never considered ES response codes as binary:) Also, I didn't know about status code in error message... All of this makes additional status not needed. 
Thanks for help:)
