### ISSUE TITLE
Connection Drop/Network drop on a Jest Client

### ISSUE THREAD

**Issue by ravinaik1312** [searchbox-io/Jest#223]
Not really an issue, but I wanted to know how Jest handles a connection/network drop. What do we need to do when a singleton jest client goes through a network drop while querying the node?

**Comment by kramer** [comment]
As stated in [here](https://github.com/searchbox-io/Jest/blob/master/jest/src/main/java/io/searchbox/client/http/JestHttpClient.java#L44) any exceptions thrown by Apache HttpClient are not handled by jest so they'll be thrown to user.
