### ISSUE TITLE
Opinions on v1.0.0

### ISSUE THREAD

**Issue by kramer** [searchbox-io/Jest#225]
Since the project has been around for almost 3 years now and seems to have gotten to a somewhat stable point (albeit missing implementation of some elasticsearch APIs) I propose making the next release [v0.1.7](https://github.com/searchbox-io/Jest/wiki/Changelog#v017-16082015) the last in 0.x minor series and therefore releasing our first major version 1.0.0 after that. It seems ideal to me having a 3 month cool down and feedback period after v0.1.7 which would then see the major release around November.

Please do share your comments, opinions and concerns!

**Comment by ferhatsb** [comment]
:) Feels right.

**Comment by bartekbp** [comment]
Great idea;)

**Comment by knight1128** [comment]
Great Idea. I am waiting for 1.0.0.!!

**Comment by PaniniGelato** [comment]
I am following the docs to play Jest. 
To use *Builders like SearchSourceBuilder, JSONBuilder etc, I have to add dependencies of ES, which are very heavy.
Could u please make much more light-weight builders in Jest?
Or any suggestions?

**Comment by kramer** [comment]
@PaniniGelato I'm sure package size is a valid concern for you but re-implementing the builders is simply something we cannot afford to maintain in jest; and considering the ever minimally changing json structure of ES and the fact that it would be an exact (functional) clone with the very little benefit of reduced size, there is just no incentive to do so.

**Comment by PaniniGelato** [comment]
@kramer understood.

**Comment by raunak** [comment]
i've been pretty content with how well the current version (0.7) has worked for me. We should defo have a 1.0 release, perhaps, include some enhancements like #244 #242

**Comment by kramer** [comment]
v1.0.0 release is now [planned for November 15th](https://github.com/searchbox-io/Jest/wiki/Changelog).

Since we also have the ES2 compatible version in branch `es_2.0`, my current plan is to release it as v2.0.0 at the same time and keep both major versions updated/released until we hit a change that can't be applied to v1.0.0; as always I'm open to suggestions.

**Comment by kramer** [comment]
Closing as v1.0.0 and v2.0.0 are now released.
`master` contains v2.0.0, and `es_1.0`branch contains v1.0.0 code.
