### ISSUE TITLE
Error when using script_fields together with from and size

### ISSUE THREAD

**Issue by cristiboariu** [searchbox-io/Jest#230]
Doing 
```
searchSourceBuilder.query(query)
searchSourceBuilder.fields(ImmutableList.of("_source"));
searchSourceBuilder.scriptField("distance", "doc['location.pin'].distanceInMiles(lat,lon)", coordScript);
```

and also:
```
searchSourceBuilder.from(response.getOffset()).size(response.getLimit());
```

it's throwing a generic exception:

```
 SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[DgXFtrciRzCvMJc-Murfow][bloom-v2][0]: RemoteTransportException[[dwalin-2][inet[/10.0.24.13:9300]][indices:data/read/search[phase/query+fetch]]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }]
```

If commenting out from and size line all works fine. Any hint?

**Comment by kramer** [comment]
Just guessing: It could be that by using from & size you get to a record which doesn't have the field you are trying to access in your script (`location.pin`) and that is causing the NullPointerException.

**Comment by cristiboariu** [comment]
Tanks kramer. What you say makes sense... Is there any option to make this distance calculation optional? (only when location.pin exists)?

**Comment by kramer** [comment]
I don't know any way to make it "optional"; what I'd do is: null check within the script and return a default value if that field doesn't exist. If that doesn't work I'd suggest asking this in ES mailing group as the question per se does not seem to be jest related.
