### ISSUE TITLE
Saving queries for percolator

### ISSUE THREAD

**Issue by raunak** [searchbox-io/Jest#236]
I'm trying to save percolate queries in ES (version 1.5.2) using JEST wrapper, however, ES does not like the query I'm passing in. Here's a snippet of what my code looks like;

    SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
    searchSourceBuilder.query(QueryBuilders.matchQuery("stock", "apple"));
    saveDoc(searchSourceBuilder, "1", "_percolator", "stocks");

    public JestResult saveDoc(Object doc, String docId, String indexName, String type) {
        Index index = new Index.Builder(doc).id(docId).index(indexName).type(type).build();
        return client.execute(index);
    }

I end up with an error "{"error":"RemoteTransportException[[kili-1][inet[/10.0.7.64:9300]][indices:data/write/index]]; nested: PercolatorException[[default] failed to parse query [1]]; nested: NullPointerException; ","status":500}"

Is there something obvious that I'm doing wrong?

**Comment by raunak** [comment]
After much debugging, it turns out if if I pass the string version of `searchSourceBuilder` (`searchSourceBuilder.toString()`) to `Index.Builder(..)`, saving queries works as expected. What I am not sure about is, why do I have to do this explicitly for SearchSourceBuilder objects, but the same isn't true for my own POJOs.

**Comment by kramer** [comment]
> why do I have to do this explicitly for SearchSourceBuilder objects, but the same isn't true for my own POJOs

That's because the former one is a `builder` not a `POJO` and GSON can't (and does not need to) handle that. As you discovered `builder.toString()` is the way to go.
