### ISSUE TITLE
Additional Metadata for Percolator

### ISSUE THREAD

**Issue by raunak** [searchbox-io/Jest#238]
Is there a way to add additional metadata to `SearchSourceBuilder` query before saving it in the index?

For example..
`{  
  "query":{  
    "match":{  
      "author":"vonnegut"
    },
    "userid":"1"
  }
}`

**Comment by kramer** [comment]
`QueryBuilder`s are part of Elasticsearch and not Jest. Please direct your question to appropriate place/authority.
