### ISSUE TITLE
Missing abstraction for Search Exists API

### ISSUE THREAD

**Issue by soliveri** [searchbox-io/Jest#242]
It would be great to support: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-exists.html

**Comment by andrejserafim** [comment]
Looks like the API you're after has been removed from the upcoming version of ES.

https://github.com/elastic/elasticsearch/issues/13682

Is it still worth implementing? also note the alternative suggested by @clintongormley.

**Comment by kramer** [comment]
> Is it still worth implementing?

Definitely no. Anyone interested should follow [the official suggestion](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-exists.html) instead:

> use regular _search with size set to 0 and terminate_after set to 1 instead.
