### ISSUE TITLE
Stats query seems to ignore addIndex

### ISSUE THREAD

**Issue by lsborg** [searchbox-io/Jest#243]
I'm querying stats and results give me all indexes even if i use addIndex. 

    JestResult result = client.execute(new Stats.Builder().build())
    JestResult result = client.execute(new Stats.Builder().addIndex(indexName).build())

Please, what am I doing wrong?

**Comment by kramer** [comment]
Tests are running fine, which version are you using (of Jest and ES server), is that your exact code?

**Comment by lsborg** [comment]
So sorry @kramer 

It is working as expected, don't know how i messed up to get the wrong result. 

Thanks for your prompt answer and sorry for wasting your time.
