### ISSUE TITLE
Inject own serializer

### ISSUE THREAD

**Issue by nicoruti** [searchbox-io/Jest#247]
Is there a feature planned to inject an own serializer?

There are various reasons:
- Use a complete other serializer implementation than Gson (for example Jackson).
- Configure the used Gson (custom serializers, etc.).

The problem I'm currently facing is that I have a ES mapping that looks uses
```
"field1": {
  "type": "date",
  "format": "date"
},
"field2": {
  "type": "date",
  "format": "dateOptionalTime"
}
```

This throws the exception:
```
! java.text.ParseException: Unparseable date: "1979-12-21"
! at java.text.DateFormat.parse(DateFormat.java:366) ~[na:1.8.0_60]
! at com.google.gson.DefaultDateTypeAdapter.deserializeToDate(DefaultDateTypeAdapter.java:105) ~[gson-2.3.1.jar:na]
! ... 78 common frames omitted
! Causing: com.google.gson.JsonSyntaxException: 1979-12-21
! at com.google.gson.DefaultDateTypeAdapter.deserializeToDate(DefaultDateTypeAdapter.java:107) ~[gson-2.3.1.jar:na]
! at com.google.gson.DefaultDateTypeAdapter.deserialize(DefaultDateTypeAdapter.java:82) ~[gson-2.3.1.jar:na]
! at com.google.gson.DefaultDateTypeAdapter.deserialize(DefaultDateTypeAdapter.java:35) ~[gson-2.3.1.jar:na]
! at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[gson-2.3.1.jar:na]
! at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) ~[gson-2.3.1.jar:na]
! at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) ~[gson-2.3.1.jar:na]
! at com.google.gson.Gson.fromJson(Gson.java:810) ~[gson-2.3.1.jar:na]
! at com.google.gson.Gson.fromJson(Gson.java:775) ~[gson-2.3.1.jar:na]
! at com.google.gson.Gson.fromJson(Gson.java:724) ~[gson-2.3.1.jar:na]
! at com.google.gson.Gson.fromJson(Gson.java:696) ~[gson-2.3.1.jar:na]
! at io.searchbox.client.JestResult.createSourceObject(JestResult.java:196) ~[jest-common-0.1.7.jar:na]
! at io.searchbox.core.SearchResult.access$000(SearchResult.java:20) [jest-common-0.1.7.jar:na]
! at io.searchbox.core.SearchResult$Hit.<init>(SearchResult.java:261) [jest-common-0.1.7.jar:na]
! at io.searchbox.core.SearchResult.extractHit(SearchResult.java:119) [jest-common-0.1.7.jar:na]
! at io.searchbox.core.SearchResult.getHits(SearchResult.java:87) [jest-common-0.1.7.jar:na]
! at io.searchbox.core.SearchResult.getHits(SearchResult.java:68) [jest-common-0.1.7.jar:na]
! at io.searchbox.core.SearchResult.getHits(SearchResult.java:64) [jest-common-0.1.7.jar:na]
```

**Comment by nicoruti** [comment]
Sorry, just saw that I could do the following:
```
JestClient jestClient = ...
JestHttpClient httpClient = (JestHttpClient) jestClient;
httpClient.setGson(...)
```

This lets me replace the Gson library with a custom configured one. Nevertheless, another serializer implementation is not supported (due to the lack of a common interface). I had a similar issue with another project of mine and solved it by providing an own interface (as it's used throughout the whole library): <a href="https://github.com/Hive2Hive/Hive2Hive/blob/master/org.hive2hive.core/src/main/java/org/hive2hive/core/serializer/IH2HSerialize.java">IH2HSerializer</a>.

**Comment by kramer** [comment]
Hi @nicoruti 
Glad you found out how to inject your own Gson instance. You are right that Jest does not support other json serializers at this point - which was extensively discussed in #45. Unfortunately json classes from Gson is used generously in various places in Jest which makes things a bit harder than using a simple interface as the one you linked. If you are interested in contributing and discussing that issue please feel free to do so in #45,
