### ISSUE TITLE
Signing Requests for AWS Elasticsearch Service

### ISSUE THREAD

**Issue by thesmith** [searchbox-io/Jest#248]
As I"m sure you noticed, AWS will now host ES for you: https://aws.amazon.com/elasticsearch-service/

Which is a big security win and pushes more people to use HTTP clients.

As it stands, I can't see an easy way to implement signing requests as demonstrated by someone here: http://pokusak.blogspot.co.uk/2015/10/aws-elasticsearch-request-signing.html

Outside of implementing my own JestClient that is...

**Comment by LosD** [comment]
I don't think the Jest client part should be a problem; subclass JestHttpClient and override prepareRequest(), something like:
```java
public class JestAWSHttpClient extends JestHTTPClient {
    private final String awsAccessKey;
    private final String awsSecretKey;
    private final String region;
    private final String service;

    public JestAWSHttpClient(final String awsAccessKey, final String awsSecretKey, final String region, final String service){
        this.awsAccessKey = awsAccessKey;
        this.awsSecretKey = awsSecretKey;
        this.region = region;
        this.service = service;
    }

    protected <T extends JestResult> HttpUriRequest prepareRequest(final Action<T> clientRequest) {
        HttpUriRequest request = super.prepareRequest(clientRequest);
        String autorizationHeader = (... Generate auth header as described by Pakusak here);
        request.addHeader("Authorization", autorizationHeader);
        return request;
    }
}
```

As far as I can see, the prepared HttpUriRequest contains everything you need to generate the authorization header; existing headers, payload and the URI (which contains both endpoint and query string).

**Comment by thesmith** [comment]
I tried that, but I ran into the problem that the underlying Apache HttpClient injects a lot of the standard headers into the request much later down the stack.

I finally got this working yesterday by overriding the client factory and injecting a RequestInterceptor at the very end of the request chain.

Once I've given it a good testing I'll share the code. Is there some kind of Jest Plugin format, or something, that I could provide it as?

**Comment by LosD** [comment]
Ahh, yeah that would of course break the header. 

I'm not sure (I'm not really a Jest contributer, though I might have something for them soon), but digging through the code I didn't see anything.

**Comment by kramer** [comment]
> Is there some kind of Jest Plugin format

Unfortunately no; you could put it in a new maven module though (`jest-ext-aws`?), that should work like a plugin if I'm not missing something.

**Comment by andrejserafim** [comment]
It sounds to me like this is a special way to create/configure jest for AWS. So a factory with that snippet sounds like a first choice. I'm not sure how you would link them though, in a sense that you may want AWS and something else as well.

**Comment by thesmith** [comment]
Ok, I created a separate project: https://github.com/inreachventures/aws-signing-request-interceptor

I'll publish it to maven central.

**Comment by LosD** [comment]
Very nice!

I'm doing a Jest based version of the ElasticSearch plugin for Apache MetaModel (the constant compatibility breaking binary of the ES Java clients are giving us a lot of trouble). We can't use it just yet as we're stuck on Java 7, but as soon as we have thrown that away, I'm totally   using your interceptor. :-)

**Comment by thesmith** [comment]
It's available now. Enjoy :)
