### ISSUE TITLE
Accept existing SSLConnectionSocketFactory / HttpClient

### ISSUE THREAD

**Issue by poblish** [searchbox-io/Jest#251]
Hi there,

There doesn't seem to be any way of constructing a `JestClientFactory` without a `HttpClientConfig.Builder`, which unavoidably calls `sslSocketFactory = SSLConnectionSocketFactory.getSocketFactory()` on instantiation. That's fair enough, but I already have a fully formed `HttpClient`, complete with a `SSLConnectionSocketFactory` (and custom `HostnameVerifier`), so it would be nicer/faster/more efficient if I could simply pass in either of the existing  SSLConnectionSocketFactory or HttpClient.

Is there any way this can be done?

**Comment by kramer** [comment]
You can pass your own `SSLConnectionSocketFactory` instance as illustrated in the [readme](https://github.com/searchbox-io/Jest/tree/master/jest#https--ssl).

**Comment by poblish** [comment]
Sorry, I probably wasn't clear enough. Yes, though I can overwrite it with my own, I'm really trying to prevent the default SSLConnectionSocketFactory getting created _at all_, because it's relatively expensive. I imagine the Builder could be changed to only create it lazily (e.g. on `build()`), but I wondered if there was a workaround...

**Comment by kramer** [comment]
As it currently stands there is no workaround to creating that default instance. I understand that moving the default assignments like `sslSocketFactory = SSLConnectionSocketFactory.getSocketFactory();` into the `build()` method would solve your problem, right? If so then I can do that change or you can also submit a pull request for that.

**Comment by poblish** [comment]
Submitted: https://github.com/searchbox-io/Jest/pull/252
