### ISSUE TITLE
Auto discovery based on cluster name?

### ISSUE THREAD

**Issue by redi-madhava** [searchbox-io/Jest#254]
I couldn't find a way to make Jest Client discover ES nodes using just cluster name. Is there a way? Otherwise could this be a feature request?

**Comment by andrejserafim** [comment]
Am I missing something? You would still need to point it to a host and port, how else jest would know where to connect to. But once you've done that you have defined the cluster.

**Comment by redi-madhava** [comment]
When you run native node on a machine, it will use standard ports to discover any other nodes in the same subnet based on the "cluster name". I was hoping for similar feature with Jest.

**Comment by ferhatsb** [comment]
There is no feature like "standard ports to discover any other nodes in the same subnet based on the "cluster name", native protocol uses localhost:9300 if you do not provide, there is no magic at all. It will discover other nodes if it can connect to one, that is called seed node.

On the other hand Jest can discover other nodes if you provide one seed and enable discovery.

**Comment by kramer** [comment]
Closing as no updates were provided recently. Please feel free to reopen if you feel you have more to add to the issue.
