### ISSUE TITLE
JestResult.setJsonObject java.lang.UnsupportedOperationException: JsonObject

### ISSUE THREAD

**Issue by Stefan-V** [searchbox-io/Jest#255]
After executing the following code: 

client.execute(new CreateIndex.Builder("testindex").build());
i get the following exception
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
	at io.searchbox.client.JestResult.setJsonObject(JestResult.java:105)

this is due to the missing implementation of the method com.google.gson.JsonElement.getAsString()
should be replaced with toString()

**Comment by kramer** [comment]
Are you using ES 2.0?

**Comment by kramer** [comment]
Closing as no updates were provided recently. Please feel free to reopen if you feel you have more to add to the issue.

**Comment by ZacharyThomas** [comment]
@kramer Ran in to this problem running ES 2.0, Jest 0.1.7. Should I wait for Jest 2.0 to fix this?

**Comment by andrejserafim** [comment]
Yes, jest 2.0 will fix the error reporting, so you can see it. It may or
may not address the underlying error, depending on what it is of course.

**Comment by kramer** [comment]
@ZacharyThomas Yes; as you can see in the [Compatibility Table](https://github.com/searchbox-io/Jest#compatibility) Jest 0.1.7 does not play nice with ES 2.0.

**Comment by ZacharyThomas** [comment]
Gotcha. Is there a way to build the es_2.0 branch source?

**Comment by kramer** [comment]
Automated [snapshot builds](https://github.com/searchbox-io/Jest/tree/master/jest#snapshot) are already on [sonatype repository](https://oss.sonatype.org/content/repositories/snapshots/io/searchbox/jest/2.0.0-SNAPSHOT/). You can use that or just checkout the branch then do `mvn clean install`.

**Comment by ZacharyThomas** [comment]
Awesome. Thanks for answering!
