### ISSUE TITLE
Add support for Amazon Elastisearch Service

### ISSUE THREAD

**Issue by malpani** [searchbox-io/Jest#264]
I wanted to propose extending Jest to support AWS Signature V4 signing which would allow for seamless integration with [Amazon Elasticsearch Service] (https://aws.amazon.com/elasticsearch-service/) 

Proposal is to take in an additional transportOptions Map while setting up the HttpClientConfig
```
{
"type": "aws" (extend to others as needed)
"region": "us-east-1", 
"service" : "es", 
secret_key, (optional)
access_key (optional)
}  
```
    config = new HttpClientConfig.Builder("https://foo.es.us-east-1.amazonaws.com:80").transportOptions(<Map>).build();`

We can have a JestHttpClientFactory which defaults to the JestHttpClient and other implementations like AmazonESJestHttpClient based on transportOptions.get("type")

**Comment by kramer** [comment]
This has been discussed before in #248 and @thesmith has created [aws-signing-request-interceptor](https://github.com/inreachventures/aws-signing-request-interceptor) for this purpose.
