### ISSUE TITLE
Jest-Droid: payload not set for POST and PUT methods

### ISSUE THREAD

**Issue by anielo** [searchbox-io/Jest#265]
For example the search action (which is translated to a POST) does not take into account my payload. After analysing the code in more detail I noticed that the JestDroidClient only sets a payload if the request is an instance of HttpEntityEnclosingRequestBase. For the classes HttpPostHC4 and HttpPutHC4 this cannot be the case. But both extend HttpEntityEnclosingRequestBaseHC4. Identical class name up to the HC4 suffix. Strange!

After digging into the history, I found commit ee7938bca7ddab38874cac101c0fc58b9f35feab which migrated the code to the official apache httpclient android port. For the class JestDroidClient this basically amounted to renaming some classes by adding the suffix HC4.

Now this smells like the HC4 has been forgotten for the class HttpEntityEnclosingRequestBase (I put a comment in the code). Am I right?

**Comment by kramer** [comment]
Hi @anielo,

Sorry for the late reply. 
Yes, your observation is correct; thanks for reporting this in! I'll be pushing a fix in a few minutes. 

p.s.: 
> Identical class name up to the HC4 suffix.

That's because android has an older (and customised IIRC) version of http client (in SDK) using the same package name and later on Apache team had to suffix classes in their newer version of the library that has the same package and class names with "HC4".

**Comment by kramer** [comment]
Fixed by 62bcd6f.

**Comment by earthiverse** [comment]
How would I go about getting these changes so I can use them in my Android application? Ideally I would like to just increment the `2.0.0` in my dependency, but it seems like builds are pushed only a couple times a year.
Is there any documentation how I can make a .jar for the latest Jest Droid code?

**Comment by kramer** [comment]
@earthiverse [Snapshot builds](https://github.com/searchbox-io/Jest/tree/master/jest#snapshot) are pushed automatically. Jest uses Maven so building (or making a jar out of it) is simply running `mvn clean install` on the checkout directory.

**Comment by earthiverse** [comment]
I got it working, thanks! This bug is fixed!
