### ISSUE TITLE
Unable to Use HttpClientConfig.builder .

### ISSUE THREAD

**Issue by phani546** [searchbox-io/Jest#267]
I have implemented JEST client to connect amazon service but when i try to implement HttpClientConfig.Builder it is throwing errors even though i added JEST jars. The error iam getting is "built path " error. i have used JEST2.0 jar.please explain me is their any jar required to get it work?
Thanks & Regards,
Phani

**Comment by kramer** [comment]
Jest uses maven to manage and provide its dependencies, there is no single standalone jar; so if you are circumventing maven's role you'll need to supply the required libraries yourself. Alternatively you might be able to build a custom standalone jar for yourself by adding the appropriate maven plugin and running the build on your machine. For both cases please refer to Google.

**Comment by phani546** [comment]
Hi Kramer,
  Thank you for the update i will check in this way.

Thanks
phani
