### ISSUE TITLE
Using the new SearchScroll API

### ISSUE THREAD

**Issue by raunak** [searchbox-io/Jest#276]
I understand the DeleteByQuery API is now deprecated, and the correct way to delete documents from ES 2.0 is to retrieve doc ids using scroll API, and use bulk delete operation. 

Perhaps, I have a wrong understanding of how to create a scroll query, but this is what I have so far. 

            SearchScroll searchScroll = new SearchScroll.Builder("", "1s")
                    .setParameter(Parameters.SEARCH_TYPE, "scan")
                    .addIndex("test")
                    .build();

The first param is the scroll id - i'm assuming this is something returned from ES to continue scrolling through results. Leaving is blank makes sense for initial query. The second param defines the duration to keep the scroll session alive. 

Now, I don't understand how I can attach a query to the searchscroll obj. Also, there isn't a addType() method? Am I missing something?

**Comment by kramer** [comment]
> Leaving is blank makes sense for initial query. 

No; you initiate a scroll context with a search query (with scroll TTL). See [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) or the [SearchScrollIntegrationTest](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/SearchScrollIntegrationTest.java).

**Comment by raunak** [comment]
Thanks @kramer. I need to pay more attention to test cases prior to posting questions :)
