### ISSUE TITLE
How do I make a partial document update

### ISSUE THREAD

**Issue by redserpent7** [searchbox-io/Jest#277]
Hi,

Is there a way to do partial updates on documents in Jest, **without using scripts**. And how would that work with the Bulk API?

**Comment by kramer** [comment]
> Is there a way to do partial updates on documents in Jest

Yes, see [UpdateIntegrationTest.partialDocUpdateWithValidParameters()](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/UpdateIntegrationTest.java#L48) for example.

> And how would that work with the Bulk API?

As expected...? What's the actual question here? Only heads up is you should not provide payload with line breaks to Bulk (same as the [rest api](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)).

**Comment by redserpent7** [comment]
Hi,

Sorry for the confusion, I am converting a .NET code using Elasticsearch-net/NEST to Java. In there we used to create a class for partial documents only containing the fields that needs to be updated. I thought there was a similar approach to that instead of having to manually write the JSON. Which I was hoping to avoid. But I guess there is no avoiding it. Thanks
