### ISSUE TITLE
NodeChecker and IdleConnectionReaper - non-daemon threads

### ISSUE THREAD

**Issue by gilbode** [searchbox-io/Jest#278]
Both NodeChecker and IdleConnectionReaper use threads that are non-daemon threads.  If you enable node discovery or connection reaping but for whatever reason fail to shutdown a JestClient the JVM hangs.  It seems that these should these should be able to be started as non-daemon threads.  Currently there is not really a hook to do this.

For NodeChecker a simple workaround is to subclass NodeChecker and override executor() and manually register a NodeChecker.  IdleConnectionReaper isn't quite as simple.

Would be nice if one way or another w/ the default JestClientFactory it would be possible to start these as daemon threads.

**Comment by kramer** [comment]
Hi @gilbode 

This concern was previously raised in #167 and at the time I falsely assumed daemon threads would be left behind alive indefinitely but now I see that they are auto-terminated in case of application exit; so thanks for bringing this up again.
