### ISSUE TITLE
push code question

### ISSUE THREAD

**Issue by developersLxz** [searchbox-io/Jest#282]
I solve this issue, but I cant push it to the repo, what should i do ?

JestResult getSourceAsString Error #280 

the issue is, original code interpret the wrong json struct, it interpret JsonArray as JsonObject.

Thanks :)

**Comment by kramer** [comment]
> I cant push it to the repo, what should i do ?

Please read the [Submission Guidelines](https://github.com/searchbox-io/Jest/blob/master/CONTRIBUTING.md#submitting-a-pull-request) which describes exactly that.
