### ISSUE TITLE
Node Discovery Issues if Whole Cluster Fails

### ISSUE THREAD

**Issue by gilbode** [searchbox-io/Jest#287]
We currently have a Jest client configured to use node discovery.  In our environment when nodes are rebooted they come up with new IP addresses.  If we enable node discovery and the entire cluster goes down we end up in a state that when the custer comes back online Jest client never reconnects.

The issue seems to be that elasticsearch sends back IP addresses (not DNS names) and once the cluster goes down and  comes back up we only have old IP addresses that are no longer valid.

It seems that Jest should be retaining the original hostnames so that if the discovered IP addresses disappear you can still reconnect to the running Elasticsearch cluster.

**Comment by andrejserafim** [comment]
+1 

I've seen this as well. The initial seed nodes provided as hostnames would still resolve to something useful.

**Comment by kramer** [comment]
Closing as fixed by #288.

**Comment by gilbode** [comment]
Any chance of a patch release sometime soon that includes this fix?
