### ISSUE TITLE
Delete by query

### ISSUE THREAD

**Issue by PeterQT** [searchbox-io/Jest#289]
I find an interesting feature called [delete by query](https://www.elastic.co/guide/en/elasticsearch/plugins/current/delete-by-query-usage.html).
How do I use it with jest client?

Thanks!

**Comment by kramer** [comment]
See [DeleteByQueryIntegrationTest](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/DeleteByQueryIntegrationTest.java) for example. You'll need the deleteByQuery plugin installed on server.
