### ISSUE TITLE
Add a TopHits aggregation

### ISSUE THREAD

**Issue by anthofo** [searchbox-io/Jest#291]
ES provides a Top Hits sub aggregation : https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-aggregations-metrics-top-hits-aggregation.html 
https://github.com/elastic/elasticsearch/blob/master/docs/java-api/aggregations/metrics/tophits-aggregation.asciidoc

Using jest, we can query ES by using the AggregationBuilders.topHits() query builder, but there is no way to get the result since the TopHits aggregation type does not exist in Jest.
We can get the parent aggregation : 
``` 
result.getAggregations().getTermsAggregation("label.raw").getBuckets()
```
But once we have the bucket entry, we can not get the TopHits subaggregation.

**Comment by bsideup** [comment]
:+1:
