### ISSUE TITLE
Need Support for ElasticSearch 2.1.1 in Jest client 2.0.0

### ISSUE THREAD

**Issue by rajadileepkolli** [searchbox-io/Jest#292]
In ElasticSearch 2.1.1 we have optimize deprecated, need to use new method hence could you release Jest 2.1.1 which is compatible with ElasticSearch 2.1.1

**Comment by kramer** [comment]
Jest version numbers do not follow ES version numbers exactly so "needing Jest 2.1.1" makes no sense. If you are saying `Optimize` action should be renamed/refactored to `ForceMerge` following the deprecation in ES then that's a valid point.

**Comment by EmilKwan** [comment]
Is Jest 2.0.0 compatible with ES 2.1.1, the latest version?

**Comment by raunak** [comment]
@EmilKwan Yes, AFAIK that is correct!

**Comment by rajadileepkolli** [comment]
@raunak Right now Jest 2.0.0 lacks few features supported in ES 2.1.1

**Comment by raunak** [comment]
That does not mean the library is not compatible with current version of
ES. I suggest you create a new ticket with the missing feature you are
after. As @cihat always says, contributions from the community are always
welcomed! :)
