### ISSUE TITLE
Multi-get with Jest?

### ISSUE THREAD

**Issue by KnowledgeGarden** [searchbox-io/Jest#293]
MultiGetRequestBuilder:
https://github.com/jprante/elasticsearch-client/blob/master/elasticsearch-client-ingest/src/main/java/org/elasticsearch/action/get/MultiGetRequestBuilder.java

needs access to an IngestClient (extends GenericClient) in order to construct an instance. There are other client types which can do this: client.prepareMultiGet()

But we do not appear to have access to such objects.

Can anyone think of a way to craft multi-get fetches with Jest?
The idea is to past a list of object id values to a request, and return all such objects in one roundtrip.

Thanks in advance for ideas.

**Comment by raunak** [comment]
There's a class called [MultiGet](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/core/MultiGet.java) in JEST which can be used for what you have described. Here's a [test case](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/test/java/io/searchbox/core/MultiGetTest.java) which shows how its used.

**Comment by KnowledgeGarden** [comment]
Precisely what the doc ordered! Sorry I missed it.
Many thanks!
