### ISSUE TITLE
How to retrieve exception feedback

### ISSUE THREAD

**Issue by jhusson** [searchbox-io/Jest#298]
Hi,

With simple client.execute() method, i don't get feedback .
I would like retrieve exception if an error occur on ES server side.

Maybe with executeAsync() but documention isn't clear about exception catching. 
For example, i got an Invalid format date error on ES side, but for Jest everything is ok ...

```
JestClient client = JestClientInstance.getInstance();
		Index index = new Index.Builder(myobj).index("test")
				.type("my_type").id(randomID).build();
		client.execute(index);
```
-------
	```	
         // format date error on ES server side
		client.executeAsync(index,new JestResultHandler<JestResult>() {
		    @Override
		    public void completed(JestResult result) {
		      // for jest request is completed
		    }
		    @Override
		    public void failed(Exception ex) {
		      
		    }
		});
```

**Comment by AlexStanovsky** [comment]
The execute method return the server result 

`JestResult result = client.execute(index);`

And then you should check what is the status of the request in the JsonObject in the result
