### ISSUE TITLE
Make JestHttpClient implement Serializable

### ISSUE THREAD

**Issue by wikier** [searchbox-io/Jest#299]
Many of the modern framework use that basic feature to serialize beans across nodes of the cluster. So for instance if you want to use it in Apache Spark you'll always face the issue: `java.io.NotSerializableException: io.searchbox.client.http.JestHttpClient`

Would be possible to get `JestHttpClient` implementing `Serializable`?

**Comment by andrejserafim** [comment]
In my mind there's 2 things here: 

1. Configuring your client
2. Opening the HTTP connections, etc.

JestHttpClient already has a handle on all of the connections and other bits specific to the jvm where it is created. Does it even make sense to ship it?

On another hand taking a factory/lambda/configuration used to instantiate a JestHttpClient and serializing that could be very useful. 

wdyt?

**Comment by wikier** [comment]
In my use case I want to:

1. Configure the client just once on the init method
2. Open connections from any node of the spark cluster

Basically I'd like to avoid creating a new client on each node on step the 2nd step. 

Currently I'm using `JestClient`, but I do not understand what you mean how `JestHttpClient` globally handles al requests at the JVM level. Could you please point me some documentation?

**Comment by rajadileepkolli** [comment]
Below is one way to get JestHttpClient which works almost like apache HttpClient    

public JestHttpClient jestClient() {
        // Construct a new Jest client according to configuration via factory
        JestClientFactory factory = new JestClientFactory();
        HttpClientConfig httpClientConfig = new HttpClientConfig.Builder(
                http://localhost:9200).multiThreaded(true).connTimeout(300)
                        .readTimeout(150)
                        .maxTotalConnection(20)
                        .gson(new GsonBuilder().setDateFormat("yyyy-MM-DD'T'hh:mm:ss").create())
                        .build();
        factory.setHttpClientConfig(httpClientConfig);
        JestHttpClient jestHttpClient = (JestHttpClient) factory.getObject();
        CloseableHttpClient closableHttpClient = HttpClientBuilder.create().build();
        jestHttpClient.setHttpClient(closableHttpClient);
        return jestHttpClient;
    }

**Comment by andrejserafim** [comment]
@wikier I meant the persistent http connections that are opened to each node in the cluster - those are associated with a specific PID. Maybe I'm missing your point.
