### ISSUE TITLE
Bulk Update

### ISSUE THREAD

**Issue by jhusson** [searchbox-io/Jest#300]
Is it possible to use Bulk Operations to update Documents ?

**Comment by andrejserafim** [comment]
The Update request is indeed bulkable. See https://github.com/searchbox-io/Jest/blob/cdd62a816a01b0d9d11262792e685396ab208e74/jest/src/test/java/io/searchbox/core/UpdateIntegrationTest.java for how to use the Update request. 

Then you just need to wrap it in a Bulk request like so https://github.com/searchbox-io/Jest/blob/eb2d90d0504a6e3db874cc8bd14efe4913451173/jest/src/test/java/io/searchbox/core/BulkIntegrationTest.java

Does that answer your question?

**Comment by jhusson** [comment]
Yes, it does !
@andrejserafim Thank you very much

Maybe a good idea to add example in official doc ;)
