### ISSUE TITLE
SearchResult.getHits should be able to return raw JsonObject hits

### ISSUE THREAD

**Issue by KonstantinYegupov** [searchbox-io/Jest#301]
Currently, SearchResult.getHits method forces you to use statically-typed classes to extract hits, with fields annotated with JestId. Even putting aside incompatibility with Jackson annotations, there's no good reason why getHits could not return hits with data represented as JsonObject and allow the user to handle the data as they see fit. 
At the very least, getHits method should be able to take JsonObject.class as an argument.

**Comment by musabgelisgen** [comment]
You can use `searchResult.getJsonObject().getAsJsonObject("hits")` to obtain results as a JsonObject where `searchResult` is a `SearchResult` instance.
