### ISSUE TITLE
Specify a type of node to autodiscover

### ISSUE THREAD

**Issue by bdharrington7** [searchbox-io/Jest#303]
The current method of discovery is pretty broad:
* connect to a node
* call `/_nodes/_all` endpoint (because no nodes were specified)
* add all nodes with an `http_address` value to the servers list. 

The problem is, this requires you to set `http.enabled: false` on the nodes you don't want serving query requests. ( i.e. master nodes). It then follows that you can't get stats from the master nodes, because `http.enabled` is set to false on them, and the http module has to be enabled to get stats out of a node. 

What is needed in this library is a way to specify which nodes you actually want to discover. Unless I missed it, there does seem to be a way to do this if you're constructing an action to get NodesInfo, but the [NodeChecker](https://github.com/searchbox-io/Jest/blob/es_1.0/jest-common/src/main/java/io/searchbox/client/config/discovery/NodeChecker.java#L31) class builds the action completely inside of itself, and there's not a way to specify which nodes to discover from the `HttpClientConfig.Builder`class

What I'm looking for is just a way to specify nodes, so that the endpoint being called will be something like 
```
_nodes/<some node attribute to filter on>/http
``` 
whereas it's currently
```
_nodes/_all/http
```

**Comment by bdharrington7** [comment]
Hi @kramer, could we discuss this or were you just waiting on a PR?

Possibly relates to #312

**Comment by kramer** [comment]
Hi @bdharrington7, sorry for the late reply. This seems like a reasonable request and I think having a user configurable string variable (e.g.: `discoveryFilter`) passed from `ClientConfig` to `NodeChecker` (which is then used to construct the nodes info action) sounds like a good solution. 

What do you think? If you agree then feel free to go ahead cook this up in a PR.

**Comment by bdharrington7** [comment]
I might have been mistaken on it being related to issue 312
