### ISSUE TITLE
Elastic 2.1 nested docs sorting

### ISSUE THREAD

**Issue by Michaloid** [searchbox-io/Jest#304]
From Elastic v2.1, if sorting by nested field then the nested_path should always be specified (Elastic 2.1.0 Breaking changes - https://github.com/elastic/elasticsearch/pull/13429).
But io.searchbox.core.search.sort.Sort do not allow definition of nested_path attribute.

Is there any workaround to add nested_path attribute to generated search query?

**Comment by gsmet** [comment]
Hi,

You probably already found a solution but the sort API is just syntactic sugar. So you can just add your sort field by manipulating the JSON directly.

**Comment by Michaloid** [comment]
That is the problem, you can't. JSON is generated inside JEST library (io.searchbox.client.JestClient.execute(Action<T> clientRequest)).
Fortunately io.searchbox.core.search.sort.Sort is not final and created inside JEST library, so I have overridden its toMap() method. It is not ideal solution, but it works.
I hope that nestedPath and mode will be added to io.searchbox.core.search.sort.Sort in next version.
Thanks

**Comment by gsmet** [comment]
AFAICS, if the sort list is empty, it doesn't add anything to the query so you can define the sort in the JSON query.

**Comment by atereques** [comment]
Hi, 
I have similar problem, IMHO **nested_path** attribute can be safely added into Sort class as it's on same level as **order** attribute.

Anyway this wouldn't be enough for me as I need to use not only nested_path but also nested filter. I've solved this by extending Sort class and converting QueryBuilder to JSON string and back to JSON object, which added into Sort.

I'm not sure whether this solution is safe to implement it in Jest client but it could help other people with similar problem.

``` java
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import io.searchbox.core.search.sort.Sort;
import lombok.Setter;
import org.apache.commons.lang.StringUtils;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;
import org.elasticsearch.index.query.QueryBuilder;

import static org.elasticsearch.common.xcontent.ToXContent.EMPTY_PARAMS;

public class ExtendedSort extends Sort {
    @Setter private String nestedPath;
    @Setter private QueryBuilder nestedQueryBuilder;

    //this is here just because variable "fieldName" is private in Sort
    private String fieldName;

    public ExtendedSort(String field) {
        super(field);
        this.fieldName = field;
    }

    public ExtendedSort(String field, Sorting order) {
        super(field, order);
        this.fieldName = field;
    }

    @Override
    public JsonObject toJsonObject() {
        JsonObject jsonObject = super.toJsonObject();

        if(StringUtils.isNotBlank(nestedPath)) {
            JsonObject sortObject = (JsonObject) jsonObject.get(fieldName);
            sortObject.add("nested_path", new JsonPrimitive(nestedPath));
            addNestedFilter(sortObject);
        }
        return jsonObject;
    }

    private void addNestedFilter(JsonObject sortObject) {
        if(nestedQueryBuilder != null) {
            String json = convertQueryBuilderToJson(nestedQueryBuilder);
            JsonElement jsonElement = new JsonParser().parse(json);
            sortObject.add("nested_filter", jsonElement.getAsJsonObject());
        }
    }

    private static String convertQueryBuilderToJson(QueryBuilder queryBuilder) {
        try {
            XContentBuilder builder = XContentFactory.jsonBuilder();
            queryBuilder.toXContent(builder, EMPTY_PARAMS);
            return builder.string();
        } catch (Exception e) {
            throw new RuntimeException("Failed to build json query.", e);
        }
    }
}
```
