### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by bjornharvold** [searchbox-io/Jest#305]
For my integration tests, I have access to embedded versions of a relational db (Derby), MongoDb(through flapdoodle) and Redis etc. I can't figure out how to do the same for Elasticsearch with Jest. Because Jest is a REST-based wrapper to Elasticsearch's API.

The only thing I can see to get to work is to have completely separate integration tests where I embed an ES Node and run the same queries there as I would in my Jest code. This obviously gives me no code coverage; only a way to see that searches work. If there were discrepancies between my Jest code and the ES Node test, I'd be out of luck.

Any suggestions would be greatly appreciated!

Cheers,
Bjorn

**Comment by kramer** [comment]
All integration tests of Jest uses ES' test package which provides a self contained ES instance;  have you already checked them?

**Comment by bjornharvold** [comment]
No I haven't. Can you point me in the right direction?

Cheers

**Comment by kramer** [comment]
See [`SearchIntegrationTest`](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/SearchIntegrationTest.java) for example.

**Comment by bjornharvold** [comment]
Great! Thank you for the help.
