### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by mpeddagolla** [searchbox-io/Jest#306]
Hi ,

We are seeing 404 Not Found on jestClient.execute operation in prod. It went to prod last sunday and since then every day once in a while it just sends 404 Not Found  for few secs and recovers again. We never had this problem locally or in our testing env. We are using AmazonElasticSearch. I would like to know if anybody has any insight on this or when this can happen?. Logger just displays 404 Not Found . 

Thank you
Mallikarjun

**Comment by alkiskal** [comment]
I don't know if I can help but it would increase your chances for an answer if you provided addtional info about your setup. 
Provide the client instantiation (properties), information about your cluster (plugins, number of nodes etc), load and any additional info (e.g. if you are using node checker). Of course omit any credentials or other information that could jeopardise the security of your infrastructure.
