### ISSUE TITLE
maxTotalConnection and defaultMaxTotalConnectionPerRoute

### ISSUE THREAD

**Issue by srdoshi** [searchbox-io/Jest#307]
Hi,

What are the suggested values for maxTotalConnection and defaultMaxTotalConnectionPerRoute in production? We have currently we have 50 each for maxTotalConnection and defaultMaxTotalConnectionPerRoute and 30sec for read timeout. We have 3 instances of our app in production with these settings.

**Comment by ferhatsb** [comment]
Defaults here;

maxConnectionsPerHost	The maximum number of connections that will be created for any particular HostConfiguration. Defaults to 2.
maxTotalConnections	The maximum number of active connections. Defaults to 20.

Jest uses Apache Http client, you can find lots of information if you search over it.
