### ISSUE TITLE
AWS node discovery fails

### ISSUE THREAD

**Issue by jacob-ewald** [searchbox-io/Jest#309]
Node discovery seems to work fine when I point to my local instance of Elasticsearch, but fails when I point to an endpoint in Amazon's Elasticsearch Service.

It appears that the client is able to connect, but doesn't discover any available nodes:

```
14:04:09.746 [NodeChecker RUNNING] DEBUG i.s.client.http.JestHttpClient - Request method=GET url=https://<AWS Endpoint>:443/_nodes/_all/http
14:04:10.263 [NodeChecker RUNNING] DEBUG io.searchbox.action.AbstractAction - Request and operation succeeded
14:04:10.264 [NodeChecker RUNNING] INFO  i.s.c.config.discovery.NodeChecker - Discovered 0 HTTP hosts: 
14:04:10.264 [NodeChecker RUNNING] WARN  i.s.client.AbstractJestClient - No servers are currently available to connect.
```

I believe it has to do with this code and the lack of `http_address` properties in the AWS response: https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/client/config/discovery/NodeChecker.java#L84
## Local (works)

```
{"cluster_name":"elasticsearch_jacobewald","nodes":{"YN_RRzvtSSi3LiJI5ga8qQ":{"name":"Living Laser","transport_address":"127.0.0.1:9300","host":"127.0.0.1","ip":"127.0.0.1","version":"2.2.0","build":"8ff36d1","http_address":"127.0.0.1:9200","settings":{"name":"Living Laser","client":{"type":"node"},"cluster":{"name":"elasticsearch_jacobewald"},"path":{"data":"/usr/local/var/elasticsearch/","logs":"/usr/local/var/log/elasticsearch","home":"/usr/local/Cellar/elasticsearch/2.2.0_1/libexec"},"config":{"ignore_system_properties":"true"}},"os"...
```
## AWS (fails)

```
{"cluster_name":"652229425299:jaketest","nodes":{"5ZWNfJyERMmYQKMsNRKA6A":{"name":"Mosha","version":"1.5.2","build":"62ff986","os"...
```

Notice the lack of any `http_address`es for the client to use. This seems to be the issue, but perhaps I'm not configuring something correctly. I'd be happy to provide any additional information that may be needed. My best guess is that Amazon expects all client access to go through that single endpoint and it handles routing to the nodes in the cluster. Is that sort of scenario supported in the JEST client?

**Comment by bdharrington7** [comment]
@jacob-ewald Off the bat I noticed you're pointing to two different versions of elasticsearch: your local is `2.2.0` and AWS is `1.5.2` There have been quite a few changes between those versions, including how nodes are reported. 

Which version of the Jest client are / were you using?

**Comment by jacob-ewald** [comment]
I believe the Jest client was version `2.0.0`. We've since moved onto a different solution, but I appreciate you looking into this issue.
