### ISSUE TITLE
DeleteByQuery does a POST instead of DELETE

### ISSUE THREAD

**Issue by camiloporto** [searchbox-io/Jest#31]
When trying to delete some documents with DeleteByQuery, the request sent is using POST Method (see DeleteByQuery.java line121).

According to ElasticSearch Guide, the http Method has to be DELETE (http://www.elasticsearch.org/guide/reference/api/delete-by-query.html)

Other problem I detect trying to deleteByQuery, is at JestHttpClient.java. On 'constructHttpMethod()' if the detected HttpMethod is DELETE, it does not put data on the request (as it does in POST option - line 117). 

So, actually, if I create a DeleteByQuery("\"match_all\" : {}") in fact the request sent is something like
curl -XPOST [server]/[index]/[type]/_query -d '{ "match_all" : {}}'
which brings a response like
{
  "ok" : true,
  "_index" : "INDEX_NAME",
  "_type" : "TYPE_NAME",
  "_id" : "_query",
  "_version" : 1
}
and delete nothing....

Instead, the generated request should be something like
curl -XDELETE '[server]/[index]/[type]/_query' -d '{
 "match_all" : {}}'

Which brings a response like 
{
  "ok" : true,
  "_indices" : {
    "INDEX_NAME" : {
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      }
    }
  }
}
this one deletes the documents.

**Comment by fcastillao** [comment]
its funny how now this method has to be post as:
![image](https://cloud.githubusercontent.com/assets/25441336/23462991/f5c80f2a-fe5d-11e6-918a-40f84c2d661d.png)
