### ISSUE TITLE
NoSuchElementException - Concurrency issue on accessing the servers

### ISSUE THREAD

**Issue by alkiskal** [searchbox-io/Jest#311]
FIrst of all thank you for this amazing library. 
Now to the point, I'm doing a stress test where there is only one ES node. Everything works great, but randomly I'm receiving the error mentioned in the title and below. I'm using one ES node. I'm using Jest 1.0.1 with ES 1.7.2

```
JestClientFactory factory = new JestClientFactory();
factory.setHttpClientConfig(new HttpClientConfig
                .Builder(restEndpoint)
                .multiThreaded(true)
                .defaultCredentials(user, password)
                .requestCompressionEnabled(false)
                .build());

this.client = factory.getObject();
```

> java.util.NoSuchElementException: null
> 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:713)
> 	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.jaThva:734)
> 	at com.google.common.collect.Iterators$4.next(Iterators.java:411)
> 	at io.searchbox.client.AbstractJestClient$ServerPool.getNextServer(AbstractJestClient.java:118)
> 	at io.searchbox.client.AbstractJestClient.getNextServer(AbstractJestClient.java:80)
> 	at io.searchbox.client.http.JestHttpClient.prepareRequest(JestHttpClient.java:80)
> 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:46)

The query is valid, as I've tested it via the marvel plugin.

**Comment by alkiskal** [comment]
Peter thank you for your help. 
How did you solve this problem in your case? Did you make changes to the source code or just added a retry policy? I'm leaning towards the second solution in order to use the official library without worrying for updates.

**Comment by peterhagelund** [comment]
Hi Alkis - you're welcome!  For now, during the research phase, I'm running with a patched 2.0.2-SNAPSHOT library as handling the exceptions is expensive.  We're looking at indexing something like ~200+ million documents in parallel across a number of nodes each with a number of threads, so speed is of the essence. I'll go look at the bulk API to get (even) better throughput - but I believe the code as it stands right now is not thread-safe, so hopefully one of the committers will make the change ;)

**Comment by alkiskal** [comment]
I agree on the performance being of the essence, particularly for that kind of usage. 
I've updated the title to highlight the importance. Thanks again Peter you've been awesome, have fun.

**Comment by alkiskal** [comment]
Hello again Peter, as you've seen I submitted a pull request for this. I followed a different approach, by implementing a simple circular list in order to avoid using sync. Take a look if interested.

**Comment by peterhagelund** [comment]
Hi Alkis - good stuff.  I'll give this a whirl in stead of what of I did.  Thanks much!
