### ISSUE TITLE
timeZone on dateHistogram send to ES "pre_zone" instead "time_zone" parametr

### ISSUE THREAD

**Issue by standam** [searchbox-io/Jest#314]
jest 2.0.1

That code:
DateHistogramBuilder agg = AggregationBuilders.dateHistogram("by_date").timeZone("+01:00")
generates:
 "pre_zone" : "+01:00" instead "time_tone" : "+01:00" in ES query

Thank you

**Comment by gsmet** [comment]
@ferhatsb these are classes from Elasticsearch, not Jest. The issue can be closed.
