### ISSUE TITLE
HttpPostHC4 does not extend HttpEntityEnclosingRequestBase, post/ put calls on android don't contain the payload

### ISSUE THREAD

**Issue by blanck1** [searchbox-io/Jest#315]
Post/ put calls on android don't contain the payload

HttpPostHC4 does not extend HttpEntityEnclosingRequestBase (http://www.atetric.com/atetric/javadoc/org.apache.httpcomponents/httpclient-android/4.3.5/org/apache/http/client/methods/HttpPostHC4.html), the same for all HC4 methods.

On the other hand all of them implement HttpEntityEnclosingRequest.
Can this be integrated in JestDroidClient.constructHttpMethod lines 85, 94?

**Comment by Digity** [comment]
I ran into the same problem.  Can someone please explain what's going on here?

**Comment by Digity** [comment]
Resolved this issue.  See here: https://github.com/searchbox-io/Jest/issues/556
