### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by magaton** [searchbox-io/Jest#321]
We are getting this exception randomly during multithreaded performance test. The same happens with both execute and executeAsync. JEST version: 2.0.1.

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:713)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
	at com.google.common.collect.Iterators$4.next(Iterators.java:411)
	at io.searchbox.client.AbstractJestClient$ServerPool.getNextServer(AbstractJestClient.java:118)
	at io.searchbox.client.AbstractJestClient.getNextServer(AbstractJestClient.java:80)
	at io.searchbox.client.http.JestHttpClient.prepareRequest(JestHttpClient.java:80)
       at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:46)

`
The config (in spring boot) is as follows:
  @Bean(destroyMethod = "shutdownClient")
    public JestClient jestClient() {
        // Configuration
        HttpClientConfig clientConfig = new HttpClientConfig.Builder("http://localhost:9200").multiThreaded(true).build();
        // Construct a new Jest client according to configuration via factory
        JestClientFactory factory = new JestClientFactory();
        factory.setHttpClientConfig(clientConfig);
        return factory.getObject();
    }
`

and the test code is:
`
final ExecutorService executor = Executors.newCachedThreadPool();
        final Set<Future<JestResult>> futures = new HashSet<>();
         final Future<JestResult> future = executor.submit(() -> {
                final long time1 = System.currentTimeMillis();
                final Search search = new Search.Builder(json)
                        .addIndex("alias")
                        .addType("type")
                        .build();
                final JestResult result = jestClient.execute(search);
                return result;
            });
            futures.add(future);
`

Any idea?
Thanks

**Comment by magaton** [comment]
After trying 2.0.2-SNAPSHOT, the problem seems to go away. Do you plan to release 2.0.2 any time soon? Thank you

**Comment by kramer** [comment]
2.0.2 is now released which should solve this issue too.
