### ISSUE TITLE
NodeChecker may set failed nodes

### ISSUE THREAD

**Issue by static-max** [searchbox-io/Jest#329]
When I set node1 as bootstrap node, jest correctly discovers my other nodes through the api.
But when node1 fails, the scheduled NodeChecker removes all discovered nodes and reverts back to the bootstrap server list (node1 in my exampe):

```
log.warn("NodesInfo request resulted in error: {}", result.getErrorMessage());
client.setServers(bootstrapServerList);
```

In that case, no communication to the cluster is possible anymore, as the bootstrap node failed and the discovered nodes are removed.

I suggest that the NodeChecker uses round-robin with all discovered nodes and that only failed nodes are removed from the server list.

**Comment by rfoltyns** [comment]
This problem will occur eventually at any node failure (literally ANY). AbstractJestClient.getNextServer() returns next entry from the ServerPool.serverIterator regardless of node type (here's the round-robin impl). So stumbling upon an unhealthy one will reset the NodeChecker to the initial list.

The thing is that NodeChecker.bootstrapServerList should be the list of high SLA servers. They should ensure that your is data stored and intact in case of failures, hence the default behaviour.

Now, Elasticsearch has it's own node discovery (Zen). The first bunch questions is:
Should the next layer over default Elasticsearch discovery be built and should this complexity be handled at NodeChecker or (Abstract)JestHttpClient level?
What should happen if all nodes fail? Should NodeChecker return to it's initial list or round-robin over nodes that are gone and will never return (e.g.: in the cloud)?
What if the last node standing is the client-node (see: [Elasticsearch docs:Node](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html)). Is your Elasticsearch based storage still healthy?

**Comment by nirajpatel** [comment]
Can we revisit this please? I am seeing the same issue on my end and it results in:

```
org.apache.http.conn.ConnectTimeoutException: Connect to 10.122.9.29:9200 [/10.122.9.29] failed: connect timed out
```

The issue is in that today's cloud world my seed Elastiscearch nodes could have been removed altogether so resetting to the `bootstrapServerList` does not work.
