### ISSUE TITLE
Aggregation inside elastic search

### ISSUE THREAD

**Issue by kdh6429** [searchbox-io/Jest#330]
As I understood, jest' aggregation works on its logic, not elastic query. It brings all data and aggregate on java side.

How should I make aggregating data on elastic side with jest? I wonder if big data will aggregate so slow and spend compute cost a lot

**Comment by ferhatsb** [comment]
Hi Kdh6429,

It is done at ES side not Jest side.

**Comment by kdh6429** [comment]
https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/search/aggregation/CardinalityAggregationIntegrationTest.java
Here is code that I saw. Is aggregation in the code at ES side? or am I looking at wrong code?
