### ISSUE TITLE
Support for Field Stats API?

### ISSUE THREAD

**Issue by tusharm** [searchbox-io/Jest#333]
Hi, 
I couldn't find a way to query for field stats. Is it on the roadmap? If not, I am willing to submit a PR.

Thanks

**Comment by kramer** [comment]
Hi @tusharm,

Field Stats API is currently not on the roadmap. Your PR would be really appreciated but considering the `This functionality is experimental and may be changed or removed completely in a future release.` [note for that API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-stats.html) I'm a bit cautious, maybe it would be better to wait until it is finalized.
