### ISSUE TITLE
Standard JestClient Gson converter causes NumberFormatException on Elastic search 1.6.X

### ISSUE THREAD

**Issue by blockmar** [searchbox-io/Jest#335]
Using the standard Gson converter causes the queries to result in a `NumberFormatException` when using Jest with Elastic 1.6.X (Not tested other versions)

Using Jest version 1.0.2.

Example:

```
HttpClientConfig.Builder httpClientConfig = new HttpClientConfig.Builder("http://localhost:9200").multiThreaded(true);

JestClientFactory factory = new JestClientFactory();
factory.setHttpClientConfig(httpClientConfig.build());
JestClient client = factory.getObject();

String query = "{ \"size\" : 1, \"query\" : { \"bool\" : { \"must\" : [ { \"term\" : { \"userId\" : 1 } }, { \"term" : { \"goalId\" : 36 } } ] } } }";

Search search = new Search.Builder(query)
                .addIndex("myindex")
                .addType("mytype")
                .addSort(new Sort("timestamp", Sort.Sorting.ASC))
                .build();

SearchResult result = jestClient.execute(search);

//Result has NumberFormatException
```

The issue is caused by the Gson converter changing all integers to decimals (eg 1 -> 1.0) when converting from a Gson map back to json string.

The query sent in: `{ "size" : 1, "query" : { "bool" : { "must" : [ { "term" : { "userId" : 1 } }, { "term" : { "goalId" : 36 } } ] } } }`

Becomes `{ "size" : 1.0, "query" : { "bool" : { "must" : [ { "term" : { "userId" : 1.0 } }, { "term" : { "goalId" : 36.0 } } ] } } }` before it's sent to elastic when adding sort.

In `io.searchbox.core.Search:84`

The solution we found was to add a custom Gson converter to the configuration that tries to prevent extra converting of integers to decimals.

```
Gson gson = new GsonBuilder()
                .setDateFormat(AbstractJestClient.ELASTIC_SEARCH_DATE_FORMAT)
                .registerTypeAdapter(Double.class,  new JsonSerializer<Double>() {
                    // Hack to remove decimals from integer values
                    @Override
                    public JsonElement serialize(Double src, Type typeOfSrc, JsonSerializationContext context) {
                        if(src == src.longValue()) {
                            return new JsonPrimitive(src.longValue());
                        }
                        return new JsonPrimitive(src);
                    }
                })
                .create();

        HttpClientConfig.Builder httpClientConfig = new HttpClientConfig.Builder(connectionUrl).multiThreaded(true).gson(gson);
...
```

**Comment by jsurls** [comment]
I ran into the same issue today using Jest 1.0.3. 

**This will only occur if you added sorting.**

From [Search.java](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/core/Search.java#L68-L90)
```Java
    public String getData(Gson gson) {
        String data;
        if (sortList.isEmpty()) {
            data = query;
        } else {
            Map<String, Object> rootJson = gson.fromJson(query, Map.class);

            List<Map<String, Object>> sortMaps = (List<Map<String, Object>>) rootJson.get("sort");
            if (sortMaps == null) {
                sortMaps = new ArrayList<Map<String, Object>>(sortList.size());
                rootJson.put("sort", sortMaps);
            }

            for (Sort sort : sortList) {
                sortMaps.add(sort.toMap());
            }

            data = gson.toJson(rootJson);
        }
        return data;
    }
```
The original "query" object had our number correctly identified as a long. However, when sort was added we deserialized it into a Map and using the default Gson in [AbstractJestClient](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/client/AbstractJestClient.java#L27-L29) when we [prepare the request](https://github.com/searchbox-io/Jest/blob/master/jest/src/main/java/io/searchbox/client/http/JestHttpClient.java#L92) we lose the original value to a double.
