### ISSUE TITLE
NodeChecker fallback to configured servers could result in DOS

### ISSUE THREAD

**Issue by bmlining** [searchbox-io/Jest#345]
For https://github.com/searchbox-io/Jest/issues/287, @gilbode enhanced NodeChecker to fallback to the configured list of servers when Node Discovery fails due to an Exception.  I ran into an issue where this behavior can cause the client to never recover:  if the configured set of servers are unavailable and do not recover.

For example, I configure my client with ServerA and Node Discovery.  My cluster may have 50 nodes, but if ServerA goes down, if the NodeChecker happens to connect to ServerA to discover the cluster nodes, it will fail and then fall back to the configured list of servers for discovery, which is just ServerA.  The only recovery path (without stopping and reconfiguring the client) is to restart ServerA.

It seems that a more reliable solution would be for NodeChecker to remove the 'defunct' server from the list of servers used by JestClient.

**Comment by bdharrington7** [comment]
@bmlining this can be closed right?

**Comment by bmlining** [comment]
https://github.com/searchbox-io/Jest/pull/367 resolves this.
