### ISSUE TITLE
Access raw http request/response for debugging/logging

### ISSUE THREAD

**Issue by btilford** [searchbox-io/Jest#346]
From what I can tell with a `JestResult` there doesn't seem to be anything other than status code available to figure out why requests are failing. Is there any way to get at the raw response body or headers? Inspecting the raw request would help too..

**Comment by kramer** [comment]
> anything other than status code 

[`getErrorMessage()`](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/client/JestResult.java#L77)

> get at the raw response body

[`getJsonString()`](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/client/JestResult.java#L69)

**Comment by btilford** [comment]
When I was debugging agains an AWS ES stack trying to authenticate with signed requests both of those  returned empty stings anytime AWS gave a 403 response.

**Comment by fraschetti** [comment]
When dealing with a large cluster, having access to the HttpUriRequest object would be nice. Currently it's impossible to know which of my nodes Jest queried which makes isolating problematic nodes near impossible.
