### ISSUE TITLE
Support for "post_filter" functionality elasticsearch

### ISSUE THREAD

**Issue by ravinaik1312** [searchbox-io/Jest#362]
Hi,

I was looking for the [post_filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-post-filter.html) functionality, but couldn't find a way to do it with Jest. Is it something that can be done alternatively with Jest or - it currently does not support it/will be supported in future releases?

Thanks,
Ravi.

**Comment by kramer** [comment]
Since search action takes the whole payload and not just the query you can do it as below but there is not a *nicer* way to accomplish it at the moment.

```java
String query = "{\n" +
            "    \"query\": {\n" +
            "        \"filtered\" : {\n" +
            "            \"query\" : {\n" +
            "                \"query_string\" : {\n" +
            "                    \"query\" : \"test\"\n" +
            "                }\n" +
            "            },\n" +
            "            \"post_filter\" : {\n" +
            "                \"term\" : { \"user\" : \"kimchy\" }\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}";

    @Test
    public void searchWithValidQuery() throws IOException {
        JestResult result = client.execute(new Search.Builder(query).build());
        assertTrue(result.getErrorMessage(), result.isSucceeded());
    }
```

**Comment by ravinaik1312** [comment]
I see. Yeah, that is what I currently have, a big query. 

Thanks,
Ravi.
