### ISSUE TITLE
Implement Snapshot API

### ISSUE THREAD

**Issue by cfuxiang** [searchbox-io/Jest#363]
Hi, 

Is there any APIs in Jest that will allow developers to create and restore snapshots? Also, it will be great to combine other libraries such as migration from old elasticsearch cluster to new elasticsearch cluser.

Thanks!

**Comment by kramer** [comment]
No, snapshot API is not implemented yet in jest. I'll leave this issue open in case anyone wants to contribute by implementing that.

**Comment by happyprg** [comment]
HI,

Can I Do that?
If you help me, I hope to implement.


2016-05-26 22:43 GMT+09:00 Cihat Keser <notifications@github.com>:

**Comment by kramer** [comment]
@happyprg Sure, go ahead.

**Comment by cfuxiang** [comment]
@kramer Thanks for the clarification. @happyprg & @kramer  I can also help in the implementation as well. Let me know if you have any suggestion in the design and we can work together. I guess an important consideration here is that we need to ensure that the feature can work in all versions of elasticsearch.

**Comment by happyprg** [comment]
Thank you for the reply to me.
First of all, I will read the other implement APIs again, and make a
prototype.
I will touch you soon.

Best Regards


2016-05-27 2:32 GMT+09:00 Fuxiang Chen <notifications@github.com>:

**Comment by cfuxiang** [comment]
@happyprg any updates? :-)

**Comment by happyprg** [comment]
Hello
Dear @kramer <https://github.com/kramer> @Chen <https://github.com/Chen>

sorry for late,
I just make a pull request about Snapshot And Restore API.
Would you please check my a pull request?

- https://github.com/searchbox-io/Jest/pull/366
thank you.





2016-05-31 14:22 GMT+09:00 Fuxiang Chen <notifications@github.com>:
