### ISSUE TITLE
Using JEST to speak to a 1.5.3 cluster and a 2.x cluster

### ISSUE THREAD

**Issue by ayounes** [searchbox-io/Jest#364]
Hi,

I have Java program that uses the native ES client JARs (1.6) to interface with a 1.5.x ES cluster.  We have a second cluster coming online soon that is 2.x which we plan to transition to.  In order to speak to both, I would need two separate Java instances with 1.x and 2.x drivers from ES.  They are not compatible.  I am thinking of using JEST to hopefully be able to speak to both clusters as we transition from 1.x to 2.x and very soon to 5.x ES.  

Based on your compatibility list, it seems that if I use JEST 2.0.0 can I speak to an ES cluster running 1.5.3?  The RESTFul api seems to be the same, so I am hoping that I can.

Thank you...Amro

**Comment by rmagen** [comment]
+1 This is my exact situation.

**Comment by kramer** [comment]
Theoretically it should work. REST APIs are not 100% same IIRC so some actions will probably not work. To know for sure you can try to run the integration test suite after changing elasticsearch test dependency version to 1.5.x. I already tried doing that but lots of test code was broken due to class name changes and whatnot so I'll leave it to a brave soul to confirm.

**Comment by andrejserafim** [comment]
I haven't tried 1.5.3, but running Jest 2 against ES 2.* and 1.7.* is perfectly fine for my use cases. Like @kramer said you have to test the specific APIs you're using. 

It helps that most changes in ES 2.0 were to turn off deprecated features. Meaning that Jest won't break, but they API you're using in elastic may not be there or may behave slightly differently.

**Comment by ayounes** [comment]
Okay thank you for the feedback.  We mainly create indices, update documents, create new ones.  The REST APIs are the same.  I noticed that groovy scripts are not deprecated in 2.x  which is something we utilize to avoid unnecessary updates to docs, and I can remove that.  I will experiment with JEST and report back our experience with a hybrid deployment until we completely transition between the old and new cluster.  I imagine we will have to do the same when we switch from 2.x to 5.x at some point too.

**Comment by bitsofinfo** [comment]
@ayounes @rmagen  can you share your results/experiences for others please?

**Comment by ayounes** [comment]
In the next few weeks I am going to transition out of using the Transport Client in java to jest so I can detail more of my experience.  We will have a cluster running 1.5.3 and a new one running 2.x.  I ran a small map/reduce using jest as the mechanism and had not issues using the latest and older versions of jest to speak to mixed ES clusters.  My findings are preliminary and will share more when I implement more code.  Time frame late august.

**Comment by rmagen** [comment]
We did a quick test that seemed to work good on 1.7 and 2.3. But haven't go we haven't done a full feature test on the 1.x branch.
