### ISSUE TITLE
Add support for multiple types to PutMapping

### ISSUE THREAD

**Issue by AssHat44** [searchbox-io/Jest#370]
PutMapping currently requires _both_ **Index** and **Type**

Support for specifying multiple types in a single request would enhance functionality over the Java Client (it doesn't support this, but the REST API does)  

see **https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html** - requests are allowed to specify just **Index** if the payload includes the **type(s)**

**Comment by happyprg** [comment]
@kramer 
Can I give it a shot?

Sent from mobile

2016. 6. 10. 오전 12:27 Steve <notifications@github.com> 작성:

**Comment by kramer** [comment]
@AssHat44 I don't see an example of this in the doc you linked. There is `PUT {index}` call with multiple mapping types but that's for creating an index. A put `PUT {index}/_mapping` would be the equivalent of what you are describing.

**Comment by AssHat44** [comment]
@kramer I Linked wrong page, but it looks like you found it. 

This improvement ticket is for abilty to specify multiple mappings at once , and is seperate from the ability to create an index with multiple mappings.

**Comment by kramer** [comment]
> but it looks like you found it

Nope... Please do point me to the page/example where this is happening :)

**Comment by happyprg** [comment]
I thought that adding below function.
am I wrong? :)
- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#_multi_index

Multi-indexedit

The PUT mapping API can be applied to multiple indices with a single request. It has the following format:

PUT /{index}/_mapping/{type}
{ body }
{index} accepts multiple index names and wildcards.
{type} is the name of the type to update.
{body} contains the mapping changes that should be applied.

**Comment by AssHat44** [comment]
Looks like support for this was removed.
The last line of this page is what I was referring to. 
Opening new improvement 'CreateIndex should allow mappings to be specified '
