### ISSUE TITLE
CreateIndex should allow mappings to be specified

### ISSUE THREAD

**Issue by AssHat44** [searchbox-io/Jest#371]
Creating an index with type mappings requires multiple actions:
CreateIndex action + x PutMapping actions 

CreateIndex should allow mappings to be specified, simplifying index creation.

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-create-index.html#mappings

**Comment by kramer** [comment]
Isn't it already supported? See: [CreateIndexIntegrationTest.java#L56](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/indices/CreateIndexIntegrationTest.java#L56).

**Comment by AssHat44** [comment]
This example is including the mapping within the json passed to CreateIndex.settings. Although this does indeed allow mapping to be specified, mappings should be given proper support.

As can be seen on the linked page: 
The Index 'Settings' object specifies shards, replicas, etc. 
'Mappings' are stored in a differnt object.

Creating an index with mappings should require 'index' and 'mappings' - not 'index' and 'settings' (which implies something else)

**Comment by kramer** [comment]
So you just mean the naming of the method `CreateIndex.Builder.settings`?

Because the scenario in the test case that I linked is structurally equivalent to the below example request given in ES docs:

```
curl -XPOST localhost:9200/test -d '{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "type1" : {
            "properties" : {
                "field1" : { "type" : "string", "index" : "not_analyzed" }
            }
        }
    }
}'
```

**Comment by AssHat44** [comment]
Settings and Mappings are two **seperate** configuration objects in Elasticsearch. They should be treated as two **seperate** parameters in CreatIndex. 

How is anyone supposed to know that they need to pass mappings within the settings parameter (especially if they know these are two different thing in Elasticsearch)? 
What if I just want to specify mappings - how does forcing it to be passed within an unrelated object make sense? 

The example IT is a workaround if anything. No documentation around this 'support' exists. (I created the issue as it appeared to be unsupported)

The term 'Settings' is not ambiguous in most cases. Jest treats _Index Settings_ as 'all index configuration'. In Elasticsearch _Index Settings_ are only one piece of the configuration. As this is a Client for Elasticsearch the definition should be that of ES.
