### ISSUE TITLE
Ability to extract source as String

### ISSUE THREAD

**Issue by aresot** [searchbox-io/Jest#372]
I need to use Jackson since we use getters/setters to de/serialize and Gson supports only property de/serialization. I tried following:

```
    for (SearchResult.Hit<String, Void> hit : topHits.getHits(String.class)) {
      Student obj = mapper.readValue(hit.source, Student.class);
      res.add(obj);
    }
```

but JestResult.createSourceObject(...) will fill source only if object has fields and as result sets source to null. So there is no obvious way to extract source as String. Would be nice if getHits(String.class) or getHits(null) will fill source with json String instead of null.

**Comment by gsmet** [comment]
@aresot can't you just test if hit.source is null before calling `mapper.readValue`?

I think it's probably better if you fix it in your code.
