### ISSUE TITLE
Google gson getAsString not implemented

### ISSUE THREAD

**Issue by coryfin** [searchbox-io/Jest#373]
The JestResult.setJsonObject method calls JsonElement.getAsString from the google gson library. However, that method is not implemented and throws an UnsupportedOperationException that is never caught. I came across this while trying to delete an index that didn't exist.

I don't know if/when the getAsString method will be implemented, but in the meantime it would be a good idea to handle that exception or use toString instead.

https://github.com/google/gson/blob/ee8d6be59ff6f2466d65be746b96ccf07ddb9ddf/gson/src/main/java/com/google/gson/JsonElement.java

**Comment by gsmet** [comment]
This one has been fixed as part of https://github.com/searchbox-io/Jest/commit/51c34af77f0babbeee9e86ea238f371a967bb707

It can be closed.
