### ISSUE TITLE
SearchResult::extractHit method doesn't extract inner_hits property from hits object

### ISSUE THREAD

**Issue by wllmtrng** [searchbox-io/Jest#380]
A query including the "inner_hits": {} returns results with a "inner_hits" property for each hit. The extractHit method currently is not extracting this property.

**Comment by wllmtrng** [comment]
#365

**Comment by wllmtrng** [comment]
Same issue as #365

**Comment by snowing0427** [comment]
It is not same issue as #365, there is no any method to return "inner_hits" property from existing result class
