### ISSUE TITLE
Support for AWS Elasticsearch Service

### ISSUE THREAD

**Issue by khundaqji** [searchbox-io/Jest#382]
AWS Elasticsearch service accepts only signed requests (AWS4 Signature that is generated from all request components [method, uri, payload, datestamp, secretkey, key ... etc]) 

Version 2.0.0 of Jest doesn't support this feature. Even doing it manually by adding the required headers to the `Search` object of jest won't solve this issue.

**Comment by marcelalburg** [comment]
Hi, 

Jest Version 2.x needs a Elasticsearch Version > 2.x. Amazons Elasticsearch Version is something like 1.5.2.

For the signing, you can check #368 - there are some good solutions.

Marcel

**Comment by khundaqji** [comment]
Hey,

Thanks for your prompt response, I have started testing this pull request modifications version made by the contributor. So far so good,

I will give a full feedback of my results.

**Comment by thesmith** [comment]
Hey @khundaqji, as mentioned in the other issue, it's worth using https://github.com/inreachventures/aws-signing-request-interceptor rather than the forked version, if possible.

**Comment by khundaqji** [comment]
@thesmith  thanks, this works very well.
I switched to  https://github.com/inreachventures/aws-signing-request-interceptor now

**Comment by marcelalburg** [comment]
Btw: Aws releases Elasticsearch v2.3
