### ISSUE TITLE
GeoDistance Sorting is not implemented

### ISSUE THREAD

**Issue by akshaypatil-bex** [searchbox-io/Jest#383]
I would like to have the capability to sort using geo distance as mentioned here

https://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-request-sort.html

**Comment by akshaypatil-bex** [comment]
@kramer Would you accept a PR for this or this there a reason it isn't done ?

**Comment by musabgelisgen** [comment]
Sure, we welcome pull requests.
