### ISSUE TITLE
when I

### ISSUE THREAD

**Issue by xiaowei1118** [searchbox-io/Jest#387]
{"error":{"root_cause":[{"type":"json_parse_exception","reason":"Unexpected character ('ä' (code 228)): was expecting comma to separate OBJECT entries\n at [Source: org.elasticsearch.transport.netty.ChannelBufferStreamInput@db08637; line: 5, column: 2055]"}],"type":"json_parse_exception","reason":"Unexpected character ('ä' (code 228)): was expecting comma to separate OBJECT entries\n at [Source: org.elasticsearch.transport.netty.ChannelBufferStreamInput@db08637; line: 5, column: 2055]"},"status":500}

**Comment by xiaowei1118** [comment]
when I update the es with id ， i rewrite a field that whese chinese，then the that happened

**Comment by xiaowei1118** [comment]
this is my content
近日，云南省政协十一届十六次常委会议在昆明召开。此次常委会，是“十三五”开局之年以来，省政协召开的第一次专题议政性常委会，围绕当前省委、省政府的中心工作，会议确定了“推进供给侧结构性改革，构建开放型、创新型和高端化、信息化、绿色化的云南特色现代产业体系”的协商主题。　　如何围绕去产能、去库存、去杠杆、降成本、补短板“五大重点任务”做好“加减乘除”？如何提高有效供给、培育新增长点、增强内生动力、化解改革阵痛？……在为期两天的会议中，省政协常委、委员和专家学者从“着力深化改革，改造提升传统产业”“推进科技创新，为产业发展提供科技支撑”“发挥资源优势，培育壮大新兴产业”“提升服务水平，营造产业发展良好环境”四个角度入题，积极建言。　　着力深化改革 改造提升传统产业　　“十二五”期间，我省全部工业增加值增长速度分别为：17.6%、15.1%、12%、7.2%、6.7%，增速大幅下降，换挡趋势明显。其中，烟草、电力、有色金属、钢铁、化工依然是5个工业总产值超过1000亿元的产业。　　同样是“十二五”期间，全省非烟工业占全部工业增加值的比重（现价）由2011年的68.7%提高到2014年的69.0%，生物医药、农特食品加工、新材料、先进装备、电子信息产业等快速发展。　　透过两组数据不难看出，云南超千亿的产业大半属于国家产能过剩并实施调控的传统产业，因此，增长不断下降成为必然，工业转型和新兴产业培育的双重压力不断增大。但值得欣慰的是，0.3%的非烟工业占比提升和新兴产业的崛起，预示着我省工业投资结构在不断改善，创新驱动战略正在发挥作用。　　“要围绕省委、省政府确定的八大产业，按照创新、协调、绿色、开放、共享的"五大发展理念"来部署、培育和构建我省新兴的产业体系。”王剑屏常委建议，要依托云南优势生物资源、特色山区农业资源、有色金属资源和重化工业基础，把云南培育成为紧贴市场的原料基地、生产体系、技术支撑体系、新产品体系和新产业体系；依托云南第三产业发展的现有基础，加速市场培育和连接、拓展产品培育和开发、提升服务管理和质量，打造新经济增长点和新支柱产业，最终完成整个经济结构的升级和经济发展方式的转变。　　其他常委们建议，着力深化改革，改造提升传统产业，就要积极稳妥地化解我省过剩产能，更加注重运用市场机制、经济手段和法治办法，加强价格、产业等政策手段的协调配合，按照“限量、重组、转移、退出”四种途径积极稳妥化解过剩产能。要进一步拓宽产业发展新空间，加快产业纵向延伸拓展，横向配套协作，发挥核心企业龙头带动作用和大中小企业集聚功能互补作用，打造若干产业集群。　　推进科技创新 为产业发展提供强大支撑　　一分创新，十分发展。对云南而言，科技，始终是产业发展中绕不开的关键问题。　　在全国上下大力推动“大众创业、万众创新”的热潮中，云南如何克服“科技创新能力弱、科技成果转化不充分、科技人才队伍不强、体制机制不健全、经费投入不足”等一系列问题，成为全省上下努力实现产业跨越发展亟待解决的核心问题。　　“科技创新要在无中生有、有中生新以及围绕我省构建"两型三化"特色现代产业体系中发挥更大作用。”刘亮常委提出，要在引进先进技术和自主创新并举，改造提升传统产业的基础上，围绕项目“科技研发—孵化加速—产业转化”的成长路线，构建多层次、立体化的载体平台支撑体系，同时抓企业主体，激发企业创新能量。　　通过案头和调研工作，夏静常委指出，当前，全球经济整体维持温和复苏态势，信息技术、生物技术、新能源技术、新材料技术等交叉融合，正在引发新一轮科技革命和产业变革，以重塑经济结构，抢占未来竞争制高点。　　“聚焦科技与经济融合，建立统筹协调的决策、监督、执行三位一体的科技管理体制。”夏静建议，要切实转变科技部门职能，由管具体项目转变为管规划、管政策、管监管、管创新环境的营造，从顶层设计上解决创新主体错位的问题；同时明确政府、企业、专家的合理分工，解决资源配置“碎片化”等突出问题。　　大家还建议，要结合云南实际，加快科技体制改革，争取实现科技创新与市场、企业有机结合；要围绕我省确定发展的八大产业，有针对性地加大科技人才团队培养力度，避免科技人员单打独斗；要通过资金项目、社会保障等措施，留好、用好、服务好现有科技人才队伍，为科技创新营造和谐稳定的环境。　　发挥资源优势 培育壮大新兴产业　　云烟、云花、云茶、云药……多年来，依托云南的特色优势资源，“云”字牌产品名声大噪，远销海内外。　　这正是云南发挥优势资源、培育壮大新兴产业的成功实践，也是协商中常委、委员和专家学者们建言关注的重点。　　“一片茶叶，记述了历史，也承载着希望，云南要继续念好"茶经"，振兴云茶产业。”对茶叶有着特殊情感的白文彬常委提出，云茶作为云南高原特色农业中的“主角”，要主打“生态、绿色、品质、安全”牌，围绕“生产有记录、信息可查询、流向可跟踪、责任可追究、质量有保障、产品可召回”目标，全面推行茶叶标准化生产和产品质量安全可追溯制度，构建茶叶质量安全监管体系。　　农工党云南省委建议，要推动花卉产业与旅游融合，将花卉纳入云南旅游(002059,股吧)二次创业的重要内容，打造具有风情浓郁、生态养生、四时花开的鲜花之旅、芳香之旅；借助烟草工业烟用香精由生物香料替代合成香料的趋势，推动花卉与烟草产业深度融合。同时，推动云花与云食、云药、云茶、外用医疗和日化产品融合，开发新产品、新市场，不断拓展花卉文化产业发展空间，努力将花卉产业培育成独具云南特色的新兴产业。　　“围绕特色资源培育特色产业、发展特色经济，是云南跨越发展的必然选择。”常委们一致认为，要在继续强化烟草、矿业、旅游、生物资源和电力等支柱产业的基础上，进一步加大对云烟、云药、云花、云茶等品牌的培植力度，加快“大健康”产业、生物医药、高原特色农业和全域旅游等产业的扶持和培育，争取更多政策和资金支持，加速资源优势向经济优势的转化。　　提升服务水平 营造产业发展良好环境　　产业要发展，服务是保障。　　十八大以来，随着政府职能的持续转变，简政放权、放管结合力度越来越大，政府从“接放管”到“放管服”，将“提升服务水平”放在了更加重要的位置。对云南而言，提升产业发展的服务水平，不是权宜之计，而是既利当前又惠长远的一项重要举措。　　王惠萍常委提出，做好产业发展的服务工作，其核心关键是把握好推进重点产业发展中需要处理好的各类关系。当前，产业发展的服务对象是各类企业，这就要求政府的服务工作从为企业营造良好的软硬环境两方面入手，既充分利用好国家支持西部地区重点基础设施建设等有利条件，推进五网建设，为产业发展提供良好的硬环境，又结合推进供给侧结构性改革五大任务，从政策上给予引导，帮助企业降低成本，减轻企业发展负担，安置好过剩产能行业的职工队伍，促进职工队伍稳定和社会稳定。　　“要将"提升服务水平，营造产业发展良好环境"作为重要任务，进一步打造优惠宽松的政策环境、优质高效的服务环境、规范严明的法制环境、崇商亲商的社会环境，全力推进现代产业体系发展，打造全省经济增长新引擎。”郭开堂常委建议，各级政府要牢固树立为人民服务理念，强化公共服务职能，进一步创新行政体制和管理方式，创造产业发展良好环境，真正成为推动我省经济和社会发展的“永动机”。　　常委们同时建议，要切实解决企业办事、融资、市场准入等方面的玻璃门、弹簧门、旋转门等推诿拖沓和不公平待遇问题；进一步优化实体经济发展环境，切实做到“一切围绕环境想，一切围绕环境转，一切围绕环境干”；进一步降低企业生产经营成本，公布收费清单，严肃查处通报各地乱收费和“不作为”情况，提高各级政府办事效率，降低企业收费负担和办事成本。　　云南日报 记者 张潇予（责任编辑： HN666）

**Comment by xiaowei1118** [comment]
this is my script and the document is the content above,thank you!!
<code>String script = "{\n" +
					"    \"lang\" : \"groovy\",\n" +
					"    \"script\" : \"ctx._source.content = tag\",\n" +
					"    \"params\" : {\n" +
					"        \"tag\" : \""+document+"\"\n" +
					"    }\n" +
					"}";</code>

**Comment by musabgelisgen** [comment]
Try to change the document encoding. Jest would normally work with utf-8 characters only.
