### ISSUE TITLE
Expose the value of _id in Hit objects

### ISSUE THREAD

**Issue by sorokod** [searchbox-io/Jest#388]
Hit exposes _index , _type, _score etc... It would be nice if we had _id as well. This is useful when post processing results and we only care about data ES returns outside of `_source`. Currently if I need to process a Hit list I need something like:

```
process( SearchResult.Hit<SomeDomainClass, ?> hit ) { ... }
```

but if I am interested only in `_id` and `_score`, and `_id` was available, I could be more general like:  

```
process( SearchResult.Hit<?, ?> hit ) { ... } 
```

**Comment by ryanrupp** [comment]
I didn't make the id available on the hit (which would be nice as well) but I did submit a PR here - https://github.com/searchbox-io/Jest/pull/400 - to make it so the id/version could be extracted without including the _source for use cases where you don't need the _source but still want to get the rest of the hit information. You would still have to have a base POJO to deserialize the id/version into though e.g.:

```
class BaseDocument {
        @JestId
        private String id;

        @JestVersion
        private Long version;

        public BaseDocument() {}

        public Long getVersion() {
            return version;
        }

        public String getId() {
            return id;
        }
}
```

Then:

```
List<Hit<BaseDocument, Void>> hits = searchResults.getHits(BaseDocument.class);
```

**Comment by a-zen** [comment]
Hi,

I aggree the id should be easily accessible for furhter use (e.g. delete, overwrite, eg.)
Currently I'm using the following to get the id:

` String documentId = searchResult.getJsonObject().getAsJsonObject("hits").getAsJsonArray("hits").get(0).getAsJsonObject().get("_id").getAsString();  `
