### ISSUE TITLE
Implement Ability to delete a type

### ISSUE THREAD

**Issue by bdharrington7** [searchbox-io/Jest#399]
I know #229 exists, but there are a few issues with deleting by query

* It's a potentially dangerous operation
* It's not supported in ES 2.x (without a plugin)
* It doesn't clear the mapping for a type

I have a use case where I actually want to delete a type and everything associated with it, so the preferable approach for me is to actually call DELETE on the type itself, as referenced in the second part of the [referenced SO answer](http://stackoverflow.com/questions/23917327/delete-all-documents-from-index-type-without-deleting-type/23918861#23918861)

**Comment by ferhatsb** [comment]
2.0 and above do not let you to do this.
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_types_may_no_longer_be_deleted

**Comment by bdharrington7** [comment]
Thanks @ferhatsb we'll have to find a workaround. Updated link: https://www.elastic.co/guide/en/elasticsearch/reference/2.2/breaking_20_mapping_changes.html#_types_may_no_longer_be_deleted
