### ISSUE TITLE
5.0 support?

### ISSUE THREAD

**Issue by ZacharyThomas** [searchbox-io/Jest#409]
Will ES 5.0 be supported by Jest?

**Comment by Simmii** [comment]
Also wondering this.

**Comment by phildav** [comment]
At least the `CreateIndex` request is not working because the HTTP method used is `POST` instead of `PUT`. `POST` is not accepted anymore by ES5, while it was before.
It looks like the HTTP method is chosen according to the value of `createOp` which is `false` for `CreateIndex`, that is quite unexpected.

**Comment by asafalima** [comment]
I've added support to some APIs in these PRs: #416, #418 and #420 
@ferhatsb It would be great if you can take a look at them so we all can use them.

**Comment by Hronom** [comment]
Guys what the progress on this?

**Comment by ferhatsb** [comment]
PRs are accepte, please let us know 5.0 related issues.

**Comment by watano** [comment]
I create a new ES project. If u need more detail info for ES 5, u can follow my project.wES-client was generated from ElasticSearch Rest API spec, so I can generate some testcase for Jest.
https://github.com/DataSays/wES
wES-client: A Java Retrofit2/OkHttp client, it was generated from ElasticSearch Rest API spec. It has two ways to visit ElasticSearch: OkHttp3 way or Retrofit2 way. So it's only depend on OkHttp3/Retrofit2, and it can support any popular Java Json lib by implement org.datasays.wes.core.IConvert interface. You can use it as you need approaches.

**Comment by scotttam** [comment]
Any ETA on when these changes will be released? Thanks.

**Comment by joshyaugustine** [comment]
It will be great if #434 can be addressed as part of this.

**Comment by katygarner** [comment]
Is there any update on node discovery working with ES5?

**Comment by eilite** [comment]
The `Search.Builder.searchType.setSearchType` with`SearchType.COUNT` doesn't work anymore in the version 5
