### ISSUE TITLE
Support per-request timeout settings.

### ISSUE THREAD

**Issue by dhay** [searchbox-io/Jest#411]
While I can set a global socket timeout setting, I'd like to specify a per-request timeout.  For example, a bulk indexing operation is expected to take longer, so I'd use a longer timeout than for most of my search requests.

This could be done in a backwards compatible manner by adding a "timeout" property to the Action interface.

**Comment by yrodiere** [comment]
Also, this kind of per-request timeout makes much sense when using APIs that have a timeout on the server side.

For instance the [Health API](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/cluster-health.html) allows to wait for an index to be "green", and offers a "timeout" parameter. It makes no sense to provide a "60s" value for the  timeout parameter to this method while the socket timeout is only 3 seconds... So we currently have to raise the global socket timeout setting to whatever (high) value we want to use in the Health API.

Ideally Jest would detect that kind of situation and just sum the timeouts, but just offering per-request timeout settings would be enough to fix the issue.

**Comment by dhay** [comment]
Perhaps if the Action has a timeout parameter (payload value?) the socket timeout should be the same? Maybe add some kind of fudge factor to account for protocol overhead?
