### ISSUE TITLE
CloseableHttpResponse is not closed in JestHttpClient.execute()

### ISSUE THREAD

**Issue by michalsida** [searchbox-io/Jest#412]
Hallo,

I think that in `JestHttpClient#execute()` is called `JestHttpClient#executeRequest,` returning `org.apache.http.client.methods.CloseableHttpResponse`, but there is not any call of `java.io.Closeable#close` on this instance, I think.

Are you sure, is it ok?

Best regards,

Michal

**Comment by epic-tylercole** [comment]
I think I'm experiencing the fallout from this. Here's the exception call stack I get that I believe is caused by this issue:

```
java.lang.IllegalStateException: Connection is still allocated
    at org.apache.http.util.Asserts.check
    at org.apache.http.impl.conn.BasicHttpClientConnectionManager.getConnection
    at org.apache.http.impl.conn.BasicHttpClientConnectionManager$1.get
    at org.apache.http.impl.execchain.MainClientExec.execute
    at org.apache.http.impl.execchain.ProtocolExec.execute
    at org.apache.http.impl.execchain.RetryExec.execute
    at org.apache.http.impl.execchain.RedirectExec.execute
    at org.apache.http.impl.client.InternalHttpClient.doExecute
    at org.apache.http.impl.client.CloseableHttpClient.execute
    at org.apache.http.impl.client.CloseableHttpClient.execute
    at io.searchbox.client.http.JestHttpClient.execute
```

**Comment by michalsida** [comment]
I prepared a fix in my fork on https://github.com/michalsida/Jest.git

Could you try it, whether it helps you? Thanks a lot.

**Comment by gsmet** [comment]
@michalsida looks good to me. Could you rebase and create a PR with your fix? It's an important bug (which might be related to https://github.com/searchbox-io/Jest/issues/136).

Thanks!

**Comment by michalsida** [comment]
Pull request is prepared, thanks.
