### ISSUE TITLE
Why SearchScroll does not implement Action<SearchResult>?

### ISSUE THREAD

**Issue by ghost** [searchbox-io/Jest#428]
Example:

        SearchScroll searchScroll = new SearchScroll.Builder(scrollId, "5m").build();
        SearchResult jestResult = (SearchResult) client.execute(searchScroll);

This code won't work since `SearchScroll` neither impement `Action<SearchResult>` nor override `createNewElasticSearchResult` method where it can create `SearchResult` (and then we would be able cast `JestResult` to that `SearchResult`).

Is there any reason not to do this? Elasticsearch responds the same structure for both `_search` and `_search/scroll` methods.

As a workaround I had to define my own `SearchScroll` which extends existing one overriding `createNewElasticSearchResult` method.

**Comment by chen56** [comment]
why?

**Comment by musabgelisgen** [comment]
You can use the following code and as far as I can see, it works fine.

```
SearchScroll searchScroll = new SearchScroll.Builder(scrollId, "5m").build();
JestResult jestResult = client.execute(searchScroll);
```
