### ISSUE TITLE
Index Stats action filters have no effect

### ISSUE THREAD

**Issue by dhayha** [searchbox-io/Jest#430]
The way the `io.searchbox.indices.Stats` class is implemented, the various builder methods (docs, store, warmer, etc.) call `setParameter`.  This doesn't have the desired effect.  It ends up building a URI that looks something like this:

someindex/_stats?docs=true&warmer=true&...

According to the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-stats.html), this URI should look like this:

someindex/_stats/docs,warmer,...

I think that the fix is to have the Builder class call `addCleanApiParameter` instead of `setParameter`. I verified this behavior with the following snippet:

```
final JestResult result = client.execute(
   new Stats.Builder()
      .addIndex("task")
      .addCleanApiParameter("docs")
      .setParameter("pretty", true)
      .build());

System.out.println(result.getJsonString());
```

**Comment by gsmet** [comment]
This was fixed by https://github.com/searchbox-io/Jest/commit/4c68a4725cc8caa72913794ad7298f108a17b50c .

I think we can close this issue.

**Comment by dhayha** [comment]
That would indeed fix it
