### ISSUE TITLE
DeleteByQuery is back on ES v5.x

### ISSUE THREAD

**Issue by watano** [searchbox-io/Jest#434]
DeleteByQuery is back on ES v5.x, pls change "/_query" to "/_delete_by_query" on io.searchbox.core.DeleteByQuery#buildURI method, and remove the comment, tks.

https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-delete-by-query.html

**Comment by bitsofinfo** [comment]
+1

**Comment by fcastillao** [comment]
this is not yet implemented in jest?

**Comment by fcastillao** [comment]
#466 merged into master
