### ISSUE TITLE
Jest client does not work for ElasticSearch version 5.0

### ISSUE THREAD

**Issue by ckrams** [searchbox-io/Jest#440]
[NodeChecker.java.txt](https://github.com/searchbox-io/Jest/files/640974/NodeChecker.java.txt)

Jest client works upto version Elastic Search 2.0 and fails to discover nodes for Elastic search Version 5.0.

Issue is tracked down to NodeChecker where the PUBLISH_ADDRESS pointing to http_address is no longer valid in version 5.0

Possible quick Solution:
NodeChecker.java
    private final static String HTTP_ADDRESS_KEY = "http_address";
    private final static String PUBLISH_ADDRESS_KEY = "publish_address";
...
		if (host.has(HTTP_ADDRESS_KEY)) {
                        JsonElement addressElement = host.get(HTTP_ADDRESS_KEY);
                        if (!addressElement.isJsonNull()) {
                            String httpAddress = getHttpAddress(addressElement.getAsString());
                            if(httpAddress != null) httpHosts.add(httpAddress);
                        }
                    }else{
                    	String httpAddress = acquirePublishAddress(host);
                    	if(null == httpAddress){
                    		log.info("Unable to resolve publish address");
                    	}else{
                    		httpHosts.add(httpAddress);
                    	}
                    }
                }

has replacement between line 95 to 101 - in this quick solution we allow both the path key to be visited to discover the publish address and will work for both ES 2.0 and ES 5.0

and add new method
	private String acquirePublishAddress(JsonObject json){
		JsonObject node = (JsonObject) json.get("http");
		if(node.has(PUBLISH_ADDRESS_KEY)){
            JsonElement addressElement = node.get(PUBLISH_ADDRESS_KEY);
            if (!addressElement.isJsonNull()) {
            	String httpAddress = getHttpAddress(addressElement.getAsString());
            	if(httpAddress != null) {
                	return httpAddress;
            	}
            }
        }
	return null;
}

I am not sure how the upload policy works and hence refraining from commit

**Comment by ravinaik1312** [comment]
Elasticsearch 5.x is not yet supported by Jest. You can probably close this ticket and track the support for 5.x under #409

**Comment by ckrams** [comment]
Above changes suggested will work for either 2.0 or 5.0 and have been tested, in case we need to continue support with existing Jest until taken over by new release it is worthwhile to patch as interim solution

**Comment by watano** [comment]
I opened my ElasticSearch related code on Github http://github.com/DataSays/wES/. This project contains an ElasticSearch Java client "wES-client". it was generated from ElasticSearch Rest API spec. so u can use it for any version for ElasticSearch.

**Comment by ferhatsb** [comment]
Guys I will release latest 2.x within this week or next and will move master to 5.0 and apply all fixes.

**Comment by ppadovani** [comment]
@ferhatsb Any update on this? thanks!

**Comment by hantuzun** [comment]
@ppadovani He's working on it.

**Comment by apatrida** [comment]
...@ferhatsb do you need more contributors that can help get things like this done incrementally?

**Comment by ferhatsb** [comment]
With some generous commits from contributors it is almost ready, travis still fails and we are at state of "works on my local". Anyway it will be fixed eventually and please have a look if we have any showstopper.
