### ISSUE TITLE
MultiSearch Query Json formatting exception through SearchSourceBuilder

### ISSUE THREAD

**Issue by sanjitvimal** [searchbox-io/Jest#441]
multisearch execution error:  Elasticsearch - 5.0, Jest- 2.0.3

sample code:
              List<Search> allQueries = new LinkedList<Search>();
		for (JestSearchRequestBuilder msreq : JestMultiSearchRequest) {
			Search search = new Search.Builder(msreq.getSearchSourceBuilder().toString())
										.addIndex(msreq.getIndice())
										.addType(msreq.getType())
										.build();
			allQueries.add(search);
		}
		MultiSearch multiSearch = new MultiSearch.Builder(allQueries).build();		
		MultiSearchResult result = jestClient.execute(multiSearch);
  
Error is :- 
{"error":{"root_cause":[{"type":"parse_exception","reason":"Exception when parsing search request"}],"type":"parse_exception","reason":"Exception when parsing search request","caused_by":{"type":"json_e_o_f_exception","reason":"Unexpected end-of-input: expected close marker for Object (start marker at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@33cd8f2f; line: 1, column: 1])\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@33cd8f2f; line: 1, column: 3]"}},"status":400}

multisearch template is like as per elasticsearch.  
{"index": "test"}
{"inline": {"query": {"match":  {"user" : "{{username}}" }}}, "params": {"username": "john"}} 
{"index": "_all", "types": "accounts"}
{"inline": {"query": {"{{query_type}}": {"name": "{{name}}" }}}, "params": {"query_type": "match_phrase_prefix", "name": "Smith"}}
{"index": "_all"}
{"id": "template_1", "params": {"query_string": "search for these words" }} 
{"types": "users"}
{"file": "template_2", "params": {"field_name": "fullname", "field_value": "john smith" }} 

all queries are in formatted(indented) in json, when we build through  SearchSourceBuilder.
i think MultiSearch.Builder() should format the query, which can be executed for _msearch, but it's not.

How to make the query which is required for _msearch execution?

**Comment by sanjitvimal** [comment]
For now i am replacing \n to " ".....
toString().replace("\n"," ")
Why formatting is not provided in MultiSearch.Builder()?

Please close the issue.

**Comment by craig-forster-sp** [comment]
I just hit this myself.  My fix what instead of using `SearchSourceBuilder#toString()` to pass to `Search.Builder`, use my own XContentBuilder to serialize it to a String.  The `toString()` method turns on pretty-printing the JSON which is what is breaking the multi-search API.

For example:

```
SearchSourceBuilder ssb = new SearchSourceBuilder();
// Build up ssb

XContentBuilder builder = XContentFactory.jsonBuilder();
ssb.toXContent( builder, ToXContent.EMPTY_PARAMS );
String ssbString = builder.string();

Search search = new Search.Builder(ssbString).build()
```

**Comment by joantune** [comment]
This isn't yet fixed in 5.3.2, 

but this commit:

https://github.com/searchbox-io/Jest/commit/a7cddb98ee5a0bca4451e2a49c2508d9cfb11171

should have fixed it

**Comment by joantune** [comment]
Alright, 5.3.3 should have it, but it isn't published on Maven yet.
@ferhatsb do you haz those powers?

**Comment by ferhatsb** [comment]
It should already released well issue is found, deployed.

**Comment by joantune** [comment]
👌  I tested it yesterday late at night with the code from the Tag 5.3.3 , it works as a charm, this issue can be closed @ferhatsb
