### ISSUE TITLE
Bulk动态插入有错误。

### ISSUE THREAD

**Issue by szwx855** [searchbox-io/Jest#442]
`List insertDoc = new ArrayList();
        for(int i = 1012;i<=1022;i++){
            Blog blog = new Blog();
            blog.setId(i);
            blog.setAddTime(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
            blog.setUpdateTime(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
            blog.setContents("okInsertTest");
            blog.setTitle("okTitle");
            blog.setType(2);
            blog.setImgsrc("e.png");
            insertDoc.add(new Index.Builder(blog));

        }

getInstance().execute(new Bulk.Builder()
                .defaultIndex("myblog")
                .defaultType("blog")
                .addAction(insertDoc)
                .build());
`
为什么会抛
java.lang.ClassCastException: io.searchbox.core.Index$Builder cannot be cast to io.searchbox.action.BulkableAction

why throws the error ?..

**Comment by smamontov** [comment]
try replace
    insertDoc.add(new Index.Builder(blog));
with
    insertDoc.add(new Index.Builder(blog).build());
