### ISSUE TITLE
[INFO] BUILD FAILURE Could not resolve dependencies for project io.searchbox:jest:jar:2.4.0

### ISSUE THREAD

**Issue by laoyang360** [searchbox-io/Jest#460]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 h
[INFO] Finished at: 2017-01-24T16:29:35+08:00
[INFO] Final Memory: 19M/157M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jest: Could not resolve dependencies for project io.searchbox:jest:jar:2.4.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.lucene:lucene-test-framework:jar:5.5.2, org.apache.lucene:lucene-core:jar:5.5.2, org.apache.lucene:lucene-querypa
rser:jar:5.5.2, io.searchbox:jest-common:jar:2.4.0-SNAPSHOT, com.barchart.udt:barchart-udt-bundle:jar:2.3.0: Could not transfer artifact org.apache.lucene:lucene-test-framework:jar:5.5.2 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/lucene/lucene-test-framework/5
.5.2/lucene-test-framework-5.5.2.jar from central failed: Premature end of Content-Length delimited message body (expected: 6548748; received: 3333545 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

E:\JAVA_SRC\Jest-master\jest>

I want to know how to resolve the problem?

**Comment by krlohnes** [comment]
@laoyang360 You have the version as `2.4.0`. The latest version 2 jar from Jest is `2.0.4` That's probably your issue.
