### ISSUE TITLE
Connecting jest with elasticsearch 5.1.1

### ISSUE THREAD

**Issue by manavbagai** [searchbox-io/Jest#461]
Earlier I was using Jest with elasticsearch 2.3 and it was working fine. Is it recommended to use jest as a client with elastic search 5.1.1.

**Comment by shalomgu** [comment]
I have made a fix and waiting for pull request merge.
https://github.com/searchbox-io/Jest/pull/459

**Comment by deepakmehtaegnyte** [comment]
is JEST v5.3.2 Compatible with ES 5.4 ??

**Comment by ferhatsb** [comment]
It should work, since it is not depended on ES, excluding some edge cases like rest api changes.
