### ISSUE TITLE
Jest 0.1.6 with Elastic search 2.4.2

### ISSUE THREAD

**Issue by wellwininfotech** [searchbox-io/Jest#463]
We are running 25 nodes ES cluster with few TBs of data. Due to resource issues we are still on ES 1.6.1 and now planning to upgrade to 2.4.2.

We want to setup 2.4.2 cluster and migrate index by index. So for while We need to support both ES 1.6.1 and ES 2.4.2 from application layer.

Would JEST 0.1.6 would work with ES 2.4.2?
If I upgrade to JEST 2.0.x, would it work with ES 1.6.1?

**Comment by phospodka** [comment]
I cannot say for your case in particular, but I have used 2.0.x of JEST to talk to elastic 1.7.4 in some basic use cases.  So a good deal of the API should work (and the opposite may as well, it is the strength of the REST API), but it will really depend on your usage as they have changed API calls.  I highly suggest looking at the breaking changes list on elastic https://www.elastic.co/guide/en/elasticsearch/reference/2.4/breaking-changes.html and work your way down to see what has changed in the API and note if you use that.  You'll probably have to change  your working version to 1.7 as well to get a full view of those changes.

**Comment by wellwininfotech** [comment]
Thanks @phospodka for answer.

Will check and revert.
