### ISSUE TITLE
Error while adding records - Failed to Parse, document is Empty 

### ISSUE THREAD

**Issue by CensusCounters** [searchbox-io/Jest#474]
Hi - I am trying to add a new record to an existing index from my android app. But I keep getting this error. 

Result JSON Object:{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"}],"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"},"status":400}

- Does this mean that the request reaching the End Point is empty? Or does it mean that I am missing some key, value pairs in the data? Or is it a formatting / field type issue?

When I print the index details that I use to send the data, it seems like it has everything needed. These are some log statements on what I am sending.

index content: {"imei_id":"123456789","count_date":"2017-03-20 08:33:20","b1":1,"b2":2,"b3":3,"b4":4}
index name: counts
index method: PUT
index uri: counts/count/1

I am able to search and get query * results back, which tells me that my url/user name/password are correct.

Any guidance will be greatly appreciated. 

Thanks

**Comment by lauraerinmann** [comment]
Where's the code for Jest?

**Comment by CensusCounters** [comment]
I was able to fix it after my post. I changed the library from 2.0.0 to 2.0.4 and it worked. Thanks
