### ISSUE TITLE
Problem with the source exclude and include with elasticsearch 5.x

### ISSUE THREAD

**Issue by rigregs** [searchbox-io/Jest#477]
In the class "io.searchbox.core.Search" there is 2 lines to include and exclude fields that aren't compatible anymore with elasticsearch 5, those attributes are deprecated:

We need to replace those 2 lines:
                addPatternListToSource(sourceObject, "include", includePatternList);
                addPatternListToSource(sourceObject, "exclude", excludePatternList);

with 
                addPatternListToSource(sourceObject, "includes", includePatternList);
                addPatternListToSource(sourceObject, "excludes", excludePatternList);

Not sure how you guys handle compatibility between newer and older versions of ES, we should do something to keep backward compatibility.

**Comment by ferhatsb** [comment]
Hi Rigregs,
I think we shoud not handle compatibility, we shoud lead users to stick with 2.x version of Jest and fix critical issues over it if any.

**Comment by rigregs** [comment]
So you guys don't plan to support elasticsearch 5.x for now?

**Comment by ferhatsb** [comment]
No, I mean yes we will support, currently master is at 5.x (not completely operational though). I meant next release will be supporting 5.x without being (now willingly, may work) 2.x compatible. If you need 2.x you need to go with Jest 2.x etc.

**Comment by rigregs** [comment]
That's great, for the moment I create my own version of the search class and change the code to be ES 5.x compatible for the exclude fields, looking forward to see that release ;)
