### ISSUE TITLE
How to add params for indexing document data

### ISSUE THREAD

**Issue by ravichaudharylnt** [searchbox-io/Jest#479]
I am using injest-attachment plugin for ES and i want to index data(as shown below) 

PUT my_index/my_type/my_id?**pipeline=attachment**
{
  "data": "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0="
}

how we can use the param(pipeline=attachment) with the jest plugin to index same data?

**Comment by alexanderzafirov** [comment]
@ravichaudharylnt I was looking through the code and found that what you need to work with is [Index](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/core/Index.java)

The problem with this abstraction is that you cannot access the `setURI` method. This means that once you have created the my_index/my_type/my_id internally, you cannot touch the URI. 

I think if the code still needs to be shielded from the messing with the exact URI, there should at least be some functionality that allows you to set the pipelines you wish (if any).

**Comment by alexanderzafirov** [comment]
Same thing goes for `_/bulk` requests.

**Comment by alexanderzafirov** [comment]
Maybe something like this https://github.com/searchbox-io/Jest/pull/513

**Comment by yuancheng-p** [comment]
Hi @alexanderzafirov, is there any update on this issue, we also need the pipeline option for the bulk ingest :)

**Comment by Romeh** [comment]
Hey all , any news about adding pipline support for Jest bulk operation ?

**Comment by musabgelisgen** [comment]
Hopefully, we will get our hands on new features after dealing with issues & bugs with Jest v6. Closing the issue for now.
