### ISSUE TITLE
Compilation error with SearchScroll

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [searchbox-io/Jest#505]
Hi,
I'm using the jest client 2.4.0 and running into compilation issues with invoking a SearchScroll action on the JestClient
 searchResult = client.execute(scroll);

Compile error: error: incompatible types: inference variable T has incompatible bounds
Could someone shed some light on this? My app runs on JDK 1.8.

Thanks,
Trang

**Comment by musabgelisgen** [comment]
You can use the following code.

`jestResult = client.execute(scroll);`
