### ISSUE TITLE
Indexing documents with "/" in the Id, double URL encoding

### ISSUE THREAD

**Issue by raja3** [searchbox-io/Jest#514]
I have a small AWS Elasticsearch cluster and I am trying to index a document with "/" in the id.

My Index object is created as follows
`
                        Index index = new Index.Builder(doc)
								.index("test-index")
								.type("test-docs")
								.refresh(true)
								.id(id)
								.build();
`
When I set id to "test/1", it fails with an AWS signing error. " ... Canonical String for this request should have been\n'PUT\n/test-index/test-docs/test%252F1 ..."

When I URL encode the Id, the call succeeds, but the document stored in elasticsearch has the _id value set to "test%2F1" instead of "test/1"

`
{

    "_index": "test-index",
    "_type": "test-docs",
    "_id": "test%2F1",
    "_version": 1,
    "_score": 1,
    "_source": {
        "id": "test%2F1",
        "base": "document-id",
        "time": 1494623016004
    }

}
`

**Comment by musabgelisgen** [comment]
Thanks for the warning. The Jest behavior for encoded URIs is changed and now, users are responsible for encoding the document id before passing it to Jest. (This is also what ES requires) These changes will apply with the next release.

```
String query = "{\n" +
                "  \"query\": {\n" +
                "    \"terms\": {\n" +
                "      \"_id\": [\"test/1\"]\n" +
                "    }\n" +
                "  }\n" +
                "}";
```
Therefore, setting the id to "test%2f1" will work as intended now, and performing a query with such string will lead to a hit.
