### ISSUE TITLE
es2.3.4 create index failed!

### ISSUE THREAD

**Issue by laoyang360** [searchbox-io/Jest#518]
I frist use jest without change pom.xml( es version is         ```
<elasticsearch.version>5.3.2</elasticsearch.version>
<lucene.version>6.4.2</lucene.version>
```

but when i create a new index using below code, 
```
 public static void main(String args[]) throws IOException {
    	System.out.println("tset!");
    	
    	// Construct a new Jest client according to configuration via factory
    	 JestClientFactory factory = new JestClientFactory();
    	 factory.setHttpClientConfig(new HttpClientConfig
    	                        .Builder("http://10.0.1.30:9200")
    	                        .multiThreaded(false)
    				//Per default this implementation will create no more than 2 concurrent connections per given route
    				.defaultMaxTotalConnectionPerRoute(2)
    				// and no more 20 connections in total
    				.maxTotalConnection(5)
    	                        .build());
    	 JestClient client = factory.getObject();
    	 
    	 client.execute(new CreateIndex.Builder("yngIndex").build());
    		System.out.println("11tset!");
    }
```
the inedx can't create failed, there is no new index in head plugin of elasticsearch.

**Comment by rfoltyns** [comment]
Try lowercase index name. That's what I got from my ES logs:
```
[yngIndex] failed to create
[yngIndex] InvalidIndexNameException[Invalid index name [yngIndex], must be lowercase]
         at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:151)
 
```

and from the JSON response:
`{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [yngIndex], must be lowercase","index_uuid":"_na_","index":"yngIndex"}],"type":"invalid_index_name_exception","reason":"Invalid index name [yngIndex], must be lowercase","index_uuid":"_na_","index":"yngIndex"},"status":400}`

**Comment by laoyang360** [comment]
@rfoltyns , yes, you are right, The reason is the index must be lowercase. 
Thank you very much!
