### ISSUE TITLE
DeleteByQuery returns wrong URI

### ISSUE THREAD

**Issue by EDKarlsson** [searchbox-io/Jest#521]
Using ES5.4.2 and I've tried this with Jest 2.4 and 5.3.2 and each time it returns the wrong URI. I've tried it with removing both type and index. The URI is still `/_query`. The URI should be `/_delete_by_query` and that this was fixed with #434.

Java:
```java
JSONObject query = new JSONObject();
query.put("query", new JSONObject().put("match", new JSONObject().put("term", new JSONObject().put(field, id))));
DeleteByQuery deleteByQuery = new DeleteByQuery.Builder(query.toString()).addType(field).addIndex(elementIndex).build();
```

Output:
```bash
JSON Query : {"query":{"match":{"term":{"_projectId":"PA"}}}}
Delete query URI : mms/_projectId/_query
Rest Method Name : DELETE
Query to String : io.searchbox.core.DeleteByQuery@63c6da4b[uri=mms/_projectId/_query,method=DELETE]
```

**Comment by EDKarlsson** [comment]
Upon inspection it seems that even though my pom specifies Jest 2.4 when I run my application it must be using an older version of Jest since the REST Method should be a post.

**Comment by urkl** [comment]
I have exactly the same problem. Is there any workround?
