### ISSUE TITLE
"[read] I/O error: Read timed out".

### ISSUE THREAD

**Issue by elasticjest** [searchbox-io/Jest#526]
I am facing the same issue, after no. of request it gives "[read] I/O error: Read timed out".

I am using below configurations.

_private static synchronized void startClient(String url){
 if(clients==null){
 clients = new ConcurrentHashMap<String,JestClient>();
 }
 boolean discovery = true;
	if(clients.isEmpty()||!clients.containsKey(url)){
		JestClientFactory factory = new JestClientFactory();
		HttpClientConfig clientConfig = new HttpClientConfig.Builder(url)
	    .multiThreaded(true)
	    .connTimeout(5000)
	    .build();
		factory.setHttpClientConfig(clientConfig);
		JestClient client = factory.getObject();
		clients.put(url, client);
	}
}

/**
 * 
 * @param url
 * @return a jest client that points to the url specified
 */
public static JestClient getClient(String url){
	if(clients==null||clients.isEmpty()||!clients.containsKey(url)){
		startClient(url);
	}
	return clients.get(url);
}_

As our Elasticsearch version is 1.1 I am using Jest 0.1.1 version, is there some version issue ?  or Am I doing something wrong here ?

**Comment by musabgelisgen** [comment]
On some systems, it may take longer than expected to process the instruction. Increase the timeout and try again.
