### ISSUE TITLE
update read me file about the supported ES version for v5.3.2 release

### ISSUE THREAD

**Issue by jackzhou** [searchbox-io/Jest#530]
I see there is a  v5.3.2 release version but I can't find out an official document about the ES version this release supports.  Can some one please provide information somewhere say the read.me file
Thanks,

**Comment by babiy8** [comment]
@joschi @hantuzun Maybe one of you could provide an answer?

**Comment by joschi** [comment]
Jest 5.3.2 supports Elasticsearch 5.3.2:
https://github.com/searchbox-io/Jest/blob/0cca426bd8343ac534984b69d73d2796c27ebe77/pom.xml#L63

Any older or newer releases of Elasticsearch 5.x *might* also work, but the tests only ran against Elasticsearch 5.3.2.

**Comment by babiy8** [comment]
Thanks
