### ISSUE TITLE
Hits are not supporting parent child

### ISSUE THREAD

**Issue by marcelalburg** [searchbox-io/Jest#543]
Elasticsearch has a parent/child feature:

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-inner-hits.html#parent-child-inner-hits

but the getHits method is not exacting _routing and _parent properties.

Marcel

**Comment by snowing0427** [comment]
how do I get "inner_hits" from SearchResult or other Result,please

**Comment by marcelalburg** [comment]
Thanks for the Release

**Comment by marcelalburg** [comment]
@ferhatsb: can you check, why the release is not in the public mvn repos ? Thanks

**Comment by ferhatsb** [comment]
Done.
