### ISSUE TITLE
TypeExist Action returns 400 Bad Request for ElasticSearch v. 5.5

### ISSUE THREAD

**Issue by akurlykov** [searchbox-io/Jest#547]
Executing TypeExist Action with Jest 5.3.2 for ES v.5.5 returns response code 400 Bad Request.

The format for that request has been changed in ES 5.
[Type Exists format for ES v.5.5](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/indices-types-exists.html) is: `HEAD twitter/_mapping/tweet`

[Type Exists format for ES v.2.4](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-types-exists.html) is: `HEAD twitter/tweet`

And Jest v.5.3.2 is still using the old format for that request.

**Workaround:**
Use GetMapping Action which will also return 404 error if the mapping doesn't exists.

**Comment by hantuzun** [comment]
Thanks @akurlykov; that's a very informative bug report. We're dealing with some urgent issues right now but we can apply your fix in a few days. 

Your pull request, maybe with a TypeExist integration test, would be highly appreciated as well!

**Comment by patelkunal** [comment]
Any updates on this?

This issue is seen on 6.x version of elasticsearch as well and all checks are passed for #561 

@ProjectOwners please merge when you get a chance.

Thanks,
/kp
