### ISSUE TITLE
How to create FiltersAggregation query using JEST builders?

### ISSUE THREAD

**Issue by dmarko484** [searchbox-io/Jest#548]
How can I create FiltersAggregation query using JEST AggregationBuilders or similar? I looked at FiltersAggregationIntegrationTest but query part is defined directly by JSON and I need something more like AggregationBuilders (as I'm using this for standard term aggregation for example)Link to FiltersAggregationIntegrationTest: https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/search/aggregation/FiltersAggregationIntegrationTest.java

See my stackoverflow post ...
https://stackoverflow.com/questions/46134364/how-to-create-filtersaggregation-query-using-jest-builders

**Comment by jmlw** [comment]
I believe you would do something along these lines:

```
QueryBuilder filterTermsQuery = QueryBuilders.termsQuery("fieldName", "value1", "value2", "value3");
        SearchSourceBuilder searchSourceBuilder = SearchSourceBuilder.searchSource()
            .query(boolQueryBuilder)
            .size(0)
            .aggregation(
                AggregationBuilders
                    .filter("filterAggName") // returns FilterAggregationBuilder
                    .filter(filterTermsQuery));
```
