### ISSUE TITLE
Use Jest with a local ES node

### ISSUE THREAD

**Issue by jobetdelima** [searchbox-io/Jest#551]
I apologize for opening an issue for this. It's just that I can't seem to find any posts related to this matter.  What Im trying to do is use Jest to set-up a local ES node on my machine for testing.  We are already using Jest to connect to ES hosted in AWS and it's working great.  We're just hoping to set-up a local ES so we could run tests as part of our build process before we deploy. 'Appreciate any lead.

**Comment by marcelalburg** [comment]
But is this a topic for jest. In general, you can use maven plugins for this or use the embedded elasticsearch. 

M

**Comment by jobetdelima** [comment]
Hi,  I've tried another ES client library before Jest and it came with support for instantiating an embedded node.  I was curious if Jest perhaps supports this out-of-the-box.  It doesn't look like it does.  Thanks for replying. Not sure if it makes sense to turn this into a feature request, but I will close this "issue".
