### ISSUE TITLE
Support for refresh=wait_for

### ISSUE THREAD

**Issue by hiren-intellectdesign** [searchbox-io/Jest#558]
ElasticSearch supports ?refresh=wait_for option as highlighted [here](https://github.com/elastic/elasticsearch/pull/17986)

How can we use it using Jest API?

Can I be helped with API documentation or example?

**Comment by urkl** [comment]
You should use it like this:


		Index index = new Index.Builder(map).index(esIndex).type(docType).id(String.valueOf(docId))

				.setParameter(**Parameters.REFRESH,"wait_for"**)
