### ISSUE TITLE
NPE when ES returns "max_score: null"

### ISSUE THREAD

**Issue by fbaligand** [searchbox-io/Jest#572]
Elasticsearch version : 5.6.3
Jest version : 5.3.3

Problem : 
If I do a search that returns 0 hits, and then call getMaxScore(), it raises a NPE here :
`io.searchbox.core.SearchResult.getMaxScore(SearchResult.java:212)`

Explanation : 
It is because ES returns 
`{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}`
So Gson deserializes "max_score" to JsonNull and not simply 'null' value.

Expected resolution : 
It would be great to test if value is 'null' or if it equals to JsonNull.INSTANCE

**Comment by musabgelisgen** [comment]
Thanks for reporting. Issue is fixed and changes are on 5.3.4 branch, will be released probably next week.

**Comment by fbaligand** [comment]
Thanks for the fix !
