### ISSUE TITLE
Scroll Integration Test

### ISSUE THREAD

**Issue by shefali026** [searchbox-io/Jest#574]
Hello,

I am referring the code for my test and I am using elastic search 5.6. On SearchScroll scroll = new SearchScroll.Builder(scrollId, "5m").build(); I am getting an error
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse request body"}],"type":"illegal_argument_exception","reason":"Failed to parse request body","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token '**********BID SCROLL ID++++++++++++++': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@4630c8b9; line: 1, column: 257]"}},"status":400}

Can somebody please help to resolve it?

**Comment by musabgelisgen** [comment]
I don't any problems with the code you mentioned. Make sure the `scrollId` string you pass is a valid string.
