### ISSUE TITLE
Support for refresh parameter on Bulk requests

### ISSUE THREAD

**Issue by ebakke** [searchbox-io/Jest#577]
Elasticsearch supports the `refresh` parameter in the [Bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-refresh) however this parameter isn't in the [`Parameters.ACCEPTED_IN_BULK`](https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/params/Parameters.java#L84) List. I assume that's why my documents aren't visible.

**Comment by musabgelisgen** [comment]
In order to see the most recent documents, you can use`refresh();` method. Also to make sure that they are searchable, use `ensureSearchable(index);` after refreshing the documents.
