### ISSUE TITLE
How to set Time To Live (TTL) with Jest?

### ISSUE THREAD

**Issue by faushine** [searchbox-io/Jest#580]

**Comment by musabgelisgen** [comment]
TTL support is removed in ES5. You can use TTL in Jest versions for ES2. Here is the Jest documentation for mapping settings in Jest v2: [PutMappingIntegrationTest.java](https://github.com/searchbox-io/Jest/blob/v2.0.2/jest/src/test/java/io/searchbox/indices/PutMappingIntegrationTest.java). 

You can pass the `_ttl` field after `properties` field as a string to a `PutMapping` instance.

For more information, please see [ES2 _ttl](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-ttl-field.html).
