### ISSUE TITLE
What is the future of JEST

### ISSUE THREAD

**Issue by zampettim** [searchbox-io/Jest#581]
Given that the Elasticsearch team is producing their own Java clients with 5.x and 6.x, what is the plan for JEST in the future? For example, is there plans to support Elasticsearch 6.1?

**Comment by sstephany** [comment]
+1.  I've been playing with Jest with ES v6.2 and so far so good.  The ES java REST client appears more limited.  For example, with Jest I can easily create an index template during application startup, which is very cool, but the ES API doesn't appear to support something like this yet.

**Comment by heartin** [comment]
If I am starting a new project with ES 6.2, should I use Jest or ES high level client?

**Comment by heartin** [comment]
Thanks @sstephany. My only concern was that I could not find any official confirmation regarding the support for 6.x. I am also doing some quick tests anyway. 

As you have mentioned about bulk indexing, could you please guide me on if there is a way to do a bulk upload from a file? Or do you manually read file into memory, populate a Bulk object and execute?

**Comment by sstephany** [comment]
Sorry @heartin, we're loading data from a DB and programmatically batch indexing.  I haven't used this API to import from a flat file, although there are probably examples out there on how to either do it programmatically, or perhaps even from logstash?

**Comment by musabgelisgen** [comment]
[Jest v6.3.0](https://github.com/searchbox-io/Jest/tree/v6.3.0) has been released.
