### ISSUE TITLE
Do you have a plan to upgrade to ElasticSearch 6.x ?

### ISSUE THREAD

**Issue by linchenhui** [searchbox-io/Jest#582]
Do you have a plan to upgrade to ElasticSearch 6.x ?

_type Deprecated in 6.0.0.

**Comment by echo-xu** [comment]
Same questions here, also for Bulk request, there is a warning: 

> Deprecated field [_routing] used, expected [routing] instead

**Comment by fbaligand** [comment]
I'm also interested by this upgrade.

**Comment by evanxuhe** [comment]
+1

**Comment by davido** [comment]
> So does that mean the library is not compatible with ES 6.x?

At least this is what ElasticVersion enum contains:

https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/client/config/ElasticsearchVersion.java#L5-L7

```
public enum ElasticsearchVersion {
    UNKNOWN,
    V2,
    V55
}
```

**Comment by heartin** [comment]
I tried out some common use cases against 6.2.4 Elastic Cloud and it is working. However wanted to be extra sure before upgrading real cluster. This is my current tests: https://github.com/heartin/elasticsearch-jest-client-usages. Anyone else did upgrade?

**Comment by SANDUO421** [comment]
BE WAITING!

**Comment by bradvido** [comment]
Also looking for 6.x support

**Comment by bitsofinfo** [comment]
+1

**Comment by bmudda** [comment]
+1

**Comment by musabgelisgen** [comment]
Jest now supports ES6. Please see [Jest v6.3.0](https://github.com/searchbox-io/Jest/tree/v6.3.0).
