### ISSUE TITLE
Add @JestIndex annotation

### ISSUE THREAD

**Issue by fbaligand** [searchbox-io/Jest#588]
It would be great to add `@JestIndex` annotation, that is applicable on a bean field.
When we search for hits on an alias or wildcard indexes, it is useful to get the source index into a dedicated field in the result hit bean.

**Comment by musabgelisgen** [comment]
I agree that it would be great to add such functionality, but currently, we are trying to fix existing bugs as much as we can. On the other hand, we accept pull requests, therefore one might come up with such an implementation and it would show up in the next releases.

**Comment by fbaligand** [comment]
I understand that this feature is not the priority.
That said, I'm sad that you close it...

I find better to have a tag like "low fruit" or "low priority".

**Comment by musabgelisgen** [comment]
Sure, I re-opened the issue for further development possibilities.

**Comment by fbaligand** [comment]
Thanks for reopening !
