### ISSUE TITLE
how to index a document with geo_point type

### ISSUE THREAD

**Issue by rabbit168** [searchbox-io/Jest#589]
how to index a document with geo_point type

**Comment by musabgelisgen** [comment]
You can use 
`index("myIndex", "myType", "myDocumentId", "{\"location\" : {\"lat\" : 30.400026, \"lon\" : -97.737343 } }");`

For more information, go to [GeoHashGridAggregationIntegrationTest.java](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/core/search/aggregation/GeoHashGridAggregationIntegrationTest.java)
