### ISSUE TITLE
 Do not support elasticsearch bulk for 6.2.3?

### ISSUE THREAD

**Issue by libra1010** [searchbox-io/Jest#590]
Do not support elasticsearch bulk for 6.2.3?

**Comment by SANDUO421** [comment]
yes ,current version is only version 5 be supported.

**Comment by musabgelisgen** [comment]
@libra1010 The new version 6.3.0 of Jest is released and Bulk API for ES6 is supported. Please see [Jest v6.3.0](https://github.com/searchbox-io/Jest/tree/v6.3.0).
