### ISSUE TITLE
jest5.3.3依赖问题

### ISSUE THREAD

**Issue by never795** [searchbox-io/Jest#594]
为什么jest5.3.3默认依赖的httpcore，httpclient版本是4.3.3。使用过程发现这两个版本缺少类org.apache.http.ssl.SSLContexts，org.apache.http.conn.ssl.DefaultHostnameVerifier，升级http版本到4.5才能运行。

**Comment by musabgelisgen** [comment]
I am closing the issue. If you have further problems, please feel free to open an issue with using the English alphabet only.
