### ISSUE TITLE
support elasticsearch 6.2.2

### ISSUE THREAD

**Issue by SANDUO421** [searchbox-io/Jest#596]
When will **elasticsearch** version **6.2.2** be supported？

**Comment by ennian001** [comment]
this ES version(6.2.2) i'm using now ,the jest version is 5.3.3,there no problem so far!!!!

**Comment by SANDUO421** [comment]
@ennian001 ： could you upload your code for us reference ? Thanks!
 my email：sanduo10086@foxmail.com.

**Comment by birjoossh** [comment]
Hi Sanduo421
I am trying to use jest 5.3.3. with elastic 6.x but seems query string isnt working.  Are you able to use query string? Can pleaee you share a sample/code snippet if possible.

**Comment by SANDUO421** [comment]
Hello Brij：
    I'm Sorry，the question has bean  always trouble me up to now. if so you dealing with it, please share me,Thanks!



sanduo10086@foxmail.com
 
From: Brij
Date: 2018-07-21 18:57
To: searchbox-io/Jest
CC: sanduo; Author
Subject: Re: [searchbox-io/Jest] support elasticsearch 6.2.2 (#596)
Hi Sanduo421
I am trying to use jest 5.3.3. with elastic 6.x but seems query string isnt working. Are you able to use query string? Can pleaee you share a sample/code snippet if possible.

**Comment by musabgelisgen** [comment]
Jest now supports ES6. Please see [Jest v6.3.0](https://github.com/searchbox-io/Jest/tree/v6.3.0).
