### ISSUE TITLE
Support elasticsearch 6.3.x - Deprecated field [_routing] used, expected [routing] instead

### ISSUE THREAD

**Issue by yuriy-slobodchikov** [searchbox-io/Jest#597]
While using routing field there are deprecation warnings in elasticsearch 6.3

[2018-07-03T10:42:20,360][WARN ][o.e.d.c.ParseField       ] Deprecated field [_routing] used, expected [routing] instead

**Comment by bitsofinfo** [comment]
Is this addressed by ? https://github.com/searchbox-io/Jest/issues/602

**Comment by bitsofinfo** [comment]
@yuriy-slobodchikov does this fix it for you? https://github.com/searchbox-io/Jest/releases/tag/v6.3.0

**Comment by musabgelisgen** [comment]
The issue is fixed in master, will be released on 6.3.1.
