### ISSUE TITLE
Add routing

### ISSUE THREAD

**Issue by fclairamb** [searchbox-io/Jest#6]
It would be great if you could add a setRouting method to add the routing parameter for the Index and Search Actions objects.

**Comment by alittleant** [comment]
The method addParameter(String, boolean) is undefined for the type Index 
how to solve it now? Thanks!

**Comment by alittleant** [comment]
for (String parameter : Parameters.ACCEPTED_IN_BULK) {
                try {
                    Collection<Object> values = **action.getParameter(parameter)**;
                    if (values != null) {
                        if (values.size() == 1) {
                            opDetails.put("_" + parameter, values.iterator().next().toString());
                        } else if (values.size() > 1) {
                            throw new IllegalArgumentException("Expecting a single value for '" + parameter + "' parameter, you provided: " + values.size());
                        }
                    }
                } catch (NullPointerException e) {
                    log.debug("Could not retrieve '" + parameter + "' parameter from action.", e);
                }
            }


is there an method named 'action.setParameter' ?
