### ISSUE TITLE
Are there plans for 6.x support?

### ISSUE THREAD

**Issue by bitsofinfo** [searchbox-io/Jest#602]
Are there plans for 6.x support?

**Comment by musabgelisgen** [comment]
Yes! We are currently working on it, thanks for your patience.

**Comment by bmudda** [comment]
@musabgelisgen Great to hear that 6.x support is in the works. What is the ETA for this? Just to get an idea since we just started using ES 6.x now.

**Comment by musabgelisgen** [comment]
Hi @bmudda, hopefully, it will be out within 2 weeks from now.

**Comment by bitsofinfo** [comment]
Is there a snapshot we could use/try?

**Comment by musabgelisgen** [comment]
Good news! Jest version 6.3.0 has been released and it is ready to use.
