### ISSUE TITLE
CatResult.parseResultArray throws java.lang.UnsupportedOperationException: JsonNull

### ISSUE THREAD

**Issue by peterbono-inttra** [searchbox-io/Jest#604]
I have an application that searches Elasticsearch indices names.

Execute a search for indices:
CatResult result = jestClient.execute(new Cat.IndicesBuilder().build());

Then retrieve array:
String[][] indicesArray = result.getPlainText();

Return index name(s) with matching search pattern.

There are several requests (4-6) that can happen at the same time. This has been working for several days without issue.

Today there two requests which threw an exception:
CatResult result = jestClient.execute(new Cat.IndicesBuilder().build());
String[][] indicesArray = result.getPlainText();
java.lang.UnsupportedOperationException: JsonNull
at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
at io.searchbox.core.CatResult.parseResultArray(CatResult.java:53)
at io.searchbox.core.CatResult.getPlainText(CatResult.java:35)
...

Should CatResult.getPlainText() check for JsonNull responses?

**Comment by musabgelisgen** [comment]
CatResult.getPlainText() already checks whether the jsonObject is null. I see there is only one line that can throw an NPE and I fixed it. The changes will apply with the next releases of Jest 5.3.4 and 6.3.1. However, I'll investigate the problem further if you can share the full stack trace with the lines that cause the exception.

**Comment by peterbono-inttra** [comment]
Thanks!

The remainder of the stack trace contains application methods leading to the call of the Jest Client. I doubt it will be much help for investigation.

I'll explain more about the application. There are 4 applications running at the same time, checking for indices, adding new ones (when new data is available) and deleting old ones (when data is expired).  It could be that Elasticsearch returned a null object in process A, for an index that was being added or deleted by process B.

**Comment by musabgelisgen** [comment]
I see your point, that might be the case. I couldn't reproduce the same exception after many trials. If you encounter the same problem again and you have more knowledge on the cause, feel free to inform us.
