### ISSUE TITLE
CreateIndex with mappings?

### ISSUE THREAD

**Issue by cmihran** [searchbox-io/Jest#606]
Is there any way to create indices using Jest with mappings as [specified here](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-create-index.html#mappings)? I see there is a settings() method in the CreateIndex.Builder but nothing for mappings. Thank you!

**Comment by musabgelisgen** [comment]
You can pass mapping of the index in addition to the settings as a String to the settings() method of CreateIndex.Builder. Here's an example of creating an index with defined settings and mappings:

```
        String index = "stringyone";
        String expectedType1Maping =
                "\"_source\":{\"enabled\":false},\"properties\":{\"field1\":{\"type\":\"keyword\"}}";
        String settingsJson = "{\n" +
                "    \"settings\" : {\n" +
                "        \"number_of_shards\" : 8\n" +
                "    },\n" +
                "    \"mappings\" : {\"type1\": {" + expectedType1Maping + "}}" +
                "}";
        CreateIndex createIndex = new CreateIndex.Builder(index)
                .settings(settingsJson)
                .build();

        JestResult result = client.execute(createIndex);
```


For more information on how to use it, checkout [CreateIndexIntegrationTest](https://github.com/searchbox-io/Jest/blob/master/jest/src/test/java/io/searchbox/indices/CreateIndexIntegrationTest.java).

In addition, I realized the settings() method does not reflect it's actual behavior. CreateIndex will be changed to provide more flexible usage in the following releases.

**Comment by cmihran** [comment]
I see, this works for my use case. Thank you!
