### ISSUE TITLE
401 Authorization Reuqired

### ISSUE THREAD

**Issue by melowYX** [searchbox-io/Jest#610]
Recently, I have a springboot project used Jest. The procedure acquire data from KAFKA then save to ElasticSearch.  But we find a question is that system log show 401 Authorization Reuqired and I/O error: Read time out. oh, my god! Surprisingly, not all http requests have such question.  In the other words,  we can find some data stored to ES successfully but some failure. Why?
   The Jest version is 5.3.3 and springboot is 1.5.9. The procedure was polyinstantiation.
   Help!!!!!

**Comment by volkflo** [comment]
Hi @melowYX,

I think I have exactly the same issue like you. You closed this issue? Can you explain how do you solved this?

```
nginx 172.20.0.1 - - [06/Dec/2018:08:24:16 +0000] "GET /apiman_gateway/dataVersion/instance HTTP/1.1" 401 195 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_181)" "-"
nginx 172.20.0.1 - test [06/Dec/2018:08:24:16 +0000] "GET /apiman_gateway/dataVersion/instance HTTP/1.1" 200 134 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_181)" "Basic dGVzdDp0ZXN0"
```

I added my logs. You can see that one request does not send the **Authorization** header

Regards,
Florian

**Comment by hiren-intellectdesign** [comment]
Hi @melowYX / @volkflo , 

We are facing exactly the same issue in our environments. Did this ever get resolved? OR any further findings?

```
10.136.99.180 - - [13/Jul/2020:11:24:44 +0700] "POST /part.index/ind-type/_search HTTP/1.1" 401 179 0.000 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_181)" "-" 0.000 -
10.136.99.180 - app-user [13/Jul/2020:11:24:44 +0700] "POST /part.index/ind-type/_search HTTP/1.1" 200 16939 0.002 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_181)" "-" 0.002 0.002
```

**Comment by volkflo** [comment]
Hi @hiren-intellectdesign,

If I remembered this correctly we set preemptive authentication. But in the meantime, we switched to the official elasticsearch client
See these lines here: https://github.com/searchbox-io/Jest/blob/fe19dc4396e08f0e03c4e749a60b8a0ed398f084/jest/src/test/java/io/searchbox/client/config/HttpClientConfigTest.java#L92-L94

HTTP authentication works like explained here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
With preemptive authentication, you will directly send the credentials with your request.

**Comment by hiren-intellectdesign** [comment]
Hi @volkflo , Thanks so much for lightening response!! Will check this out.
